In [1]:
import numpy as np
import pandas as pd

In [4]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [5]:
df=pd.read_csv('independent-house.csv')
df.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [6]:
df.shape

(1095, 21)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1095 non-null   str
 1   link             1095 non-null   str
 2   society          471 non-null    str
 3   price            968 non-null    str
 4   rate             1054 non-null   str
 5   area             1095 non-null   str
 6   areaWithType     987 non-null    str
 7   bedRoom          987 non-null    str
 8   bathroom         987 non-null    str
 9   balcony          987 non-null    str
 10  additionalRoom   589 non-null    str
 11  address          1031 non-null   str
 12  noOfFloor        967 non-null    str
 13  facing           674 non-null    str
 14  agePossession    987 non-null    str
 15  nearbyLocations  913 non-null    str
 16  description      1036 non-null   str
 17  furnishDetails   743 non-null    str
 18  features         674 non-null    str
 19  rating           907 non-null    str
 20  property_id      1036 non-null   str
dtypes: str(21)
memory usage: 2.1 MB

In [8]:
df.duplicated().sum()

np.int64(13)

In [9]:
df.drop_duplicates(inplace=True)

In [11]:
df.isnull().sum()

property_name        0
link                 0
society            619
price              127
rate                41
area                 0
areaWithType       108
bedRoom            108
bathroom           108
balcony            108
additionalRoom     504
address             64
noOfFloor          127
facing             420
agePossession      108
nearbyLocations    182
description         59
furnishDetails     350
features           420
rating             188
property_id         59
dtype: int64

In [12]:
df.drop(columns=['link','property_id'],inplace=True)

In [14]:
df.head(1)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [15]:
df.rename(columns={'rate':'price_per_sqft'},inplace=True)

In [16]:
df['society'].value_counts()

society
Emaar MGF Marbella                                   26
International City by SOBHA Phase 2                  26
Vipul Tatvam Villa                                   25
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             14
DLF City Plots Phase 2                               11
Unitech Espace                                       11
DLF City Plots                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      8
Uppal Southend4.0 ★                                   8
Not Applicable                                        7
Sushant Lok 1 Builder Floors                          6
Ansals Palam Vihar                                    6
Experion Windchants3.8 ★                              5
DLF City Phase 1                                      5
Ansal Sushant Lok Plots4.1 ★                          4
nul                                                   4
DLF New Town Heights 24.0 ★                           4
Ansals Florence Villa                                 4
DLF Alameda                                           4
Unitech Aspen Greens                                  4
Unitech Nirvana Birch Court                           4
Vatika India Next4.1 ★                                4
DLF City Plots Phase 3                                3
Puri Diplomatic Greens4.0 ★                           3
Tata Primanti4.1 ★                                    3
Anant Raj Estates                                     3
Central Park Flower Valley                            3
Bestech Park View Ananda4.2 ★                         3
HUDA Ashok Vihar Phase 13.9 ★                         3
Hans Enclave                                          3
Housing Board Colony                                  3
Malibu Towne                                          3
Sector 14 RWA                                         3
Palam Vihar Extension West Zone RWA                   3
Rattan Garden                                         3
SS Aaron Ville                                        3
Vatika Signature Villas                               3
Eros Rosewood City4.0 ★                               3
Eros Rosewood Villas                                  3
BPTP Astaire Gardens3.7 ★                             3
Silverglades Tarudhan Valley Golf Resort              3
Luxury DLF City Floors                                2
Ansal API Esencia3.7 ★                                2
Suncity Essel Towers4.2 ★                             2
Ansal Sushant Residency                               2
DLF South City 1                                      2
Emaar Emerald Hills4.1 ★                              2
Unitech Deerwood Chase                                2
DLF City Plots Phase 4                                2
shivpuri                                              2
Spaze Privy3.9 ★                                      2
Project Mianwali Colony                               2
Project Housing Board Colony                          2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Sobha City                                            2
Ardee City3.8 ★                                       2
Signature Global City 92                              2
Unitech Escape3.8 ★                                   2
Satya The Hermitage3.5 ★                              2
Suncity Township4.1 ★                                 2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
SS Hibiscus                                           2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Grover Homes Sec 4                                    1
FLOOR WISE DESIGNER KOTHI                             1
sector 37                                             1
DLF New Town Heights3.7 ★                             1
All Punjabi Welfare Association                       1
huda sector-56 gurgaon                                1
Sector-17C                                            1
private house                                         1
Anant Raj Manor Villas                                1
patel nager house no 927/5                            1
Ashok Vihar Phase 3 Gurgaon                           1
Farrukhnagar                                          1
Prem Kunj                                             1
secter 16a daultabad faridabad house no 313           1
rajendra park sec 105                                 1
Ansal Heights3.2 ★                                    1
Ninex City                                            1
Signature Global Park4.0 ★                            1
My Home                                               1
Surat nagar phase 2                                   1
DLF Gardencity Enclave                                1
Rajendra Park Gurgaon                                 1
house number B-34                                     1
ATS Tourmaline3.9 ★                                   1
Bhawani enclave                                       1
Om Nagar, Sector-11                                   1
DLF The Arbour                                        1
DLF Garden City Floors                                1
Huda Plots                                            1
Tulip Ivory3.5 ★                                      1
Emaar MGF The Palm Drive4.1 ★                         1
bhim nagar, sector 6                                  1
Anamika Enclave                                       1
Laxman vihar phase 2                                  1
MANOHAR NAGAR                                         1
Vatika Sovereign Next                                 1
Surendra Homes Dayanand Colony                        1
DLF The Grove                                         1
RK Excelo                                             1
Anand Garden, Sector-105                              1
Jacobpura Gurugram                                    1
Hero Homes                                            1
Ganpati Heights Apartment                             1
Smart World Gems                                      1
shree krishna homes                                   1
Tulip Yellow                                          1
HUDA Housing Board Colony4.1 ★                        1
Laxmi Garden Sector-11                                1
Ansal Celebrity Homes                                 1
Shri Shyam Residency                                  1
mian wali                                             1
HUDA Plot Sector 38                                   1
ROW HOUSE                                             1
Madan puri                                            1
Indiabulls Centrum Park3.7 ★                          1
Jacobpura                                             1
Huda Flats                                            1
Krishna Palace                                        1
Naman Residency                                       1
Sai Kripa Floors 5                                    1
DLF City Plot Phase 4                                 1
Bhim Nagar Society                                    1
Shivaji Nagar Residential                             1
Raj Villas                                            1
mahavir pura                                          1
jacob pura                                            1
Nirmal Enclave, Maruti Kunj Road                      1
Ansal Esencia Sovereign Floors                        1
Greenopolis                                           1
Vipul World3.9 ★                                      1
Sare Crescent Parc Royal Greens Phase 1               1
Anshul                                                1
SS Omnia                                              1
Suncity Avenue 76                                     1
Sheetla Enclave                                       1
sneh vihar                                            1
Adani Brahma Samsara4.2 ★                             1
DLF City Plot Phase 3                                 1
Signature Global City 63A                             1
rattan vihar rajendra park                            1
Ashok vihar phase III Extension                       1
Ansal                                                 1
Nitin Vihar                                           1
Sector 15 Part 2 RWA                                  1
u block dlf phase 3 road no 21                        1
cloudnine cottages                                    1
Landmark House                                        1
nirvana country                                       1
Kothi                                                 1
Birla Navya                                           1
Central Park Flower Valley Cerise Floors              1
Ansal API Spanish Court                               1
4S Aradhya Homes                                      1
Ireo Victory Valley4.1 ★                              1
Ansal Florence Super                                  1
Smart World Orchard                                   1
Unitech South City 23.8 ★                             1
DLF Floors Phase 3                                    1
Signature Global City                                 1
Signature Global City 81                              1
Central Park                                          1
Ansal Sushant Lok                                     1
Nirvana Country                                       1
Vatika The Seven Lamps3.8 ★                           1
Unitech Greenwood City3.6 ★                           1
Independent House Sector 45                           1
Ireo Victory Valley4.0 ★                              1
Satya The Legend3.8 ★                                 1
DLF Pink Town House4.0 ★                              1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Vatika Independent Floors3.8 ★                        1
The Laburnum                                          1
Ansal Sushant Lok 2                                   1
Godrej Meridien                                       1
Sector 57 Huda                                        1
Huda                                                  1
Huda Floor                                            1
Name: count, dtype: int64

In [17]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip().lower())

In [18]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,nan,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,nan,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,nan,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,nan,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [20]:
df['society']=df['society'].replace('nan','independent')

In [22]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [23]:
df['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
5 Crore             13
4.5 Crore           13
70 Lac              13
75 Lac              13
50 Lac              13
8 Crore             13
8.5 Crore           12
7 Crore             12
85 Lac              12
4 Crore             11
1.5 Crore           11
9 Crore             10
10 Crore            10
2.5 Crore           10
2.25 Crore          10
90 Lac              10
45 Lac              10
60 Lac              10
Price on Request    10
12 Crore             9
2 Crore              9
9.5 Crore            9
1.1 Crore            9
80 Lac               9
1.7 Crore            9
1 Crore              8
1.6 Crore            8
4.6 Crore            8
11 Crore             8
6.75 Crore           8
2.1 Crore            7
3.75 Crore           7
12.5 Crore           7
65 Lac               7
55 Lac               7
95 Lac               7
1.3 Crore            7
1.2 Crore            7
1.35 Crore           7
40 Lac               7
5.7 Crore            6
13.5 Crore           6
6.25 Crore           6
3.25 Crore           6
7.5 Crore            6
3.6 Crore            6
1.45 Crore           6
2.75 Crore           6
1.15 Crore           6
2.95 Crore           6
16 Crore             6
4.25 Crore           6
10.5 Crore           6
3 Crore              5
15 Crore             5
4.75 Crore           5
5.6 Crore            5
7.25 Crore           5
35 Lac               5
2.8 Crore            5
1.25 Crore           5
1.8 Crore            5
38 Lac               5
5.25 Crore           4
8.25 Crore           4
3.3 Crore            4
13 Crore             4
5.8 Crore            4
5.75 Crore           4
17 Crore             4
3.2 Crore            4
11.5 Crore           4
6.8 Crore            4
42 Lac               4
2.4 Crore            4
37 Lac               4
4.7 Crore            4
1.65 Crore           4
1.4 Crore            4
4.35 Crore           4
18 Crore             4
9.25 Crore           4
20 Crore             3
1.95 Crore           3
4.45 Crore           3
7.35 Crore           3
3.4 Crore            3
8.4 Crore            3
7.2 Crore            3
5.65 Crore           3
1.55 Crore           3
3.85 Crore           3
3.1 Crore            3
6.95 Crore           3
2.2 Crore            3
82 Lac               3
1.16 Crore           3
34 Lac               3
49 Lac               3
62 Lac               3
2.3 Crore            3
32 Lac               3
5.15 Crore           3
92 Lac               3
1.85 Crore           3
4.3 Crore            3
1.9 Crore            3
2.9 Crore            3
19 Crore             3
6.4 Crore            3
10.85 Crore          2
11.95 Crore          2
2.55 Crore           2
3.55 Crore           2
10.45 Crore          2
19.5 Crore           2
67 Lac               2
3.05 Crore           2
6.3 Crore            2
58 Lac               2
11.25 Crore          2
66 Lac               2
48 Lac               2
36 Lac               2
1.75 Crore           2
30 Lac               2
14 Crore             2
1.05 Crore           2
3.35 Crore           2
3.15 Crore           2
89 Lac               2
9.9 Crore            2
2.15 Crore           2
58.25 Lac            2
15.5 Crore           2
10.55 Crore          2
3.65 Crore           2
26 Crore             2
3.51 Crore           2
8.49 Crore           2
4.95 Crore           2
7.1 Crore            2
11.75 Crore          2
10.75 Crore          1
7.6 Crore            1
10.56 Crore          1
5.46 Crore           1
55.11 Lac            1
7.49 Crore           1
12.39 Crore          1
5.4 Crore            1
7.99 Crore           1
8.8 Crore            1
7.69 Crore           1
8.7 Crore            1
6.2 Crore            1
5.9 Crore            1
5.85 Crore           1
5.35 Crore           1
6.6 Crore            1
61 Lac               1
7.05 Crore           1
3.69 Crore           1
11.3 Crore           1
4.02 Crore           1
3.93 Crore           1
15.5 Lac             1
4.12 Crore           1
1.87 Crore           1
22 Lac               1
3.12 Crore           1
7.5 Lac              1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
1.72 Crore           1
78 Lac               1
1.52 Crore           1
52 Lac               1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
5.2 Crore            1
42.75 Lac            1
47 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
29 Lac               1
24 Lac               1
44 Lac               1
83 Lac               1
98 Lac               1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
13 Lac               1
96 Lac               1
18.02 Crore          1
65.8 Lac             1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
3.87 Crore           1
1.39 Crore           1
59 Lac               1
27 Lac               1
8.1 Crore            1
14.75 Crore          1
9.54 Crore           1
17.3 Crore           1
18.9 Crore           1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.99 Crore           1
6.81 Crore           1
8.81 Crore           1
8.9 Crore            1
4.49 Crore           1
22 Crore             1
4.15 Crore           1
7.3 Crore            1
18.5 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
5.1 Crore            1
3.9 Crore            1
2.01 Crore           1
5.88 Crore           1
52.75 Lac            1
46.75 Lac            1
12.25 Crore          1
9.4 Crore            1
10.3 Crore           1
8.45 Crore           1
6.15 Crore           1
2.47 Crore           1
3.7 Crore            1
18.4 Crore           1
4.4 Crore            1
99 Lac               1
2.65 Crore           1
1.27 Crore           1
11.29 Crore          1
4.31 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
5.51 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
1.04 Crore           1
9.85 Crore           1
1.18 Crore           1
15.1 Crore           1
9.01 Crore           1
9.8 Crore            1
4.99 Crore           1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [26]:
df[df['price']=='Price on Request']

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
295,2 Bedroom House for sale in Sector 8 Gurgaon,independent,Price on Request,NaN,(74 sq.m.) Built-up Area,Built Up area: 800 (74.32 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 8 Gurgaon, Gurgaon, Haryana",1 Floors,NaN,undefined,NaN,"1 bath, semi-Furnished, at sector 8 location g...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
296,3 Bedroom House for sale in Dharam Colony,independent,Price on Request,NaN,(93 sq.m.) Carpet Area,Carpet area: 1000 (92.9 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Dharam Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, at dharam colony location...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
325,5 Bedroom House for sale in Laxman Vihar,independent,Price on Request,NaN,(167 sq.m.) Built-up Area,Built Up area: 1800 (167.23 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,NaN,"Phase 2, Laxman Vihar, Gurgaon, Haryana",2 Floors,North,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","8 bath, unfurnished, overlooking main road, no...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
326,3 Bedroom House for sale in Laxman Vihar,independent,Price on Request,NaN,(223 sq.m.) Built-up Area,Built Up area: 2400 (222.97 sq.m.)Carpet area:...,3 Bedrooms,4 Bathrooms,2 Balconies,NaN,"1248 B, Near Hanuman Mandir, Laxman Vihar, Gur...",2 Floors,NaN,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","4 bath, unfurnished, 1st floor (Of 2), 1 side ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
402,7 Bedroom House for sale in Rajendra Park,independent,Price on Request,NaN,(585 sq.m.) Built-up Area,Built Up area: 700 (585.29 sq.m.),7 Bedrooms,6 Bathrooms,3 Balconies,NaN,"Rajendra Park, Gurgaon, Haryana",4 Floors,NaN,5 to 10 Year Old,NaN,"6 bath, furnished, 2 side open, at rajendra pa...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
431,3 Bedroom House for sale in Ansal Plaza,independent,Price on Request,NaN,(40 sq.m.) Carpet Area,Carpet area: 429 (39.86 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Ansal Plaza, Sector 23, Ansal Plaza, Gurgaon, ...",4 Floors,NaN,undefined,NaN,Best in class property available at ansal plaz...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
494,2 Bedroom House for sale in Sheetla Colony,independent,Price on Request,NaN,(42 sq.m.) Plot Area,Plot area 50(41.81 sq.m.)Built Up area: 720 sq...,2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sheetla Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, semi-Furnished, at sheetla colony loca...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5..."
569,5 Bedroom House for sale in Surat Nagar,independent,Price on Request,NaN,(54 sq.m.) Built-up Area,Built Up area: 65 (54.35 sq.m.),5 Bedrooms,2 Bathrooms,No Balcony,NaN,"Surat Nagar Phase 2, Sector 104, Surat Nagar, ...",2 Floors,NaN,undefined,NaN,5bhk residential house for resale in surat nag...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5..."
595,2 Bedroom House for sale in Dharam Colony Block E,independent,Price on Request,NaN,(84 sq.m.) Built-up Area,Built Up area: 900 (83.61 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Dharam Colony Block E, Gurgaon, Haryana",1 Floors,NaN,undefined,"['Palam triangle', 'Palam Vihar Vyapar kendra'...","1 bath, unfurnished, ground floor (Of 1), at d...",NaN,NaN,NaN
668,4 Bedroom House for sale in Madanpuri,independent,Price on Request,NaN,(167 sq.m.) Carpet Area,Carpet area: 1800 (167.23 sq.m.),4 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Madanpuri, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 1 side open, at madan pur...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [29]:
df=df[df['price']!='Price on Request']

In [30]:
def convert_to_crore(value):
    value = str(value).strip().lower()

    if 'crore' in value:
        return float(value.replace('crore', '').strip())

    elif 'lac' in value or 'lakh' in value:
        num = (
            value.replace('lac', '')
                 .replace('lakh', '')
                 .strip()
        )
        return float(num) / 100

    return None  # or float(value) if needed

In [32]:
df['price']=df['price'].apply(convert_to_crore)

In [33]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [34]:
df['price'].value_counts()

price
3.5000     19
5.5000     17
6.5000     16
6.0000     14
5.0000     13
4.5000     13
0.7000     13
0.7500     13
0.5000     13
8.0000     13
8.5000     12
7.0000     12
0.8500     12
4.0000     11
1.5000     11
9.0000     10
10.0000    10
2.5000     10
2.2500     10
0.9000     10
0.4500     10
0.6000     10
12.0000     9
2.0000      9
9.5000      9
1.1000      9
0.8000      9
1.7000      9
1.0000      8
1.6000      8
4.6000      8
11.0000     8
6.7500      8
2.1000      7
3.7500      7
12.5000     7
0.6500      7
0.5500      7
0.9500      7
1.3000      7
1.2000      7
1.3500      7
0.4000      7
5.7000      6
13.5000     6
6.2500      6
3.2500      6
7.5000      6
3.6000      6
1.4500      6
2.7500      6
1.1500      6
2.9500      6
16.0000     6
4.2500      6
10.5000     6
3.0000      5
15.0000     5
4.7500      5
5.6000      5
7.2500      5
0.3500      5
2.8000      5
1.2500      5
1.8000      5
0.3800      5
5.2500      4
8.2500      4
3.3000      4
13.0000     4
5.8000      4
5.7500      4
17.0000     4
3.2000      4
11.5000     4
6.8000      4
0.4200      4
2.4000      4
0.3700      4
4.7000      4
1.6500      4
1.4000      4
4.3500      4
18.0000     4
9.2500      4
20.0000     3
1.9500      3
4.4500      3
7.3500      3
3.4000      3
8.4000      3
7.2000      3
5.6500      3
1.5500      3
3.8500      3
3.1000      3
6.9500      3
2.2000      3
0.8200      3
1.1600      3
0.3400      3
0.4900      3
0.6200      3
2.3000      3
0.3200      3
5.1500      3
0.9200      3
1.8500      3
4.3000      3
1.9000      3
2.9000      3
19.0000     3
6.4000      3
10.8500     2
11.9500     2
2.5500      2
3.5500      2
10.4500     2
19.5000     2
0.6700      2
3.0500      2
6.3000      2
0.5800      2
11.2500     2
0.6600      2
0.4800      2
0.3600      2
1.7500      2
0.3000      2
14.0000     2
1.0500      2
3.3500      2
3.1500      2
0.8900      2
9.9000      2
2.1500      2
0.5825      2
15.5000     2
10.5500     2
3.6500      2
26.0000     2
3.5100      2
8.4900      2
4.9500      2
7.1000      2
11.7500     2
10.7500     1
7.6000      1
10.5600     1
5.4600      1
0.5511      1
7.4900      1
12.3900     1
5.4000      1
7.9900      1
8.8000      1
7.6900      1
8.7000      1
6.2000      1
5.9000      1
5.8500      1
5.3500      1
6.6000      1
0.6100      1
7.0500      1
3.6900      1
11.3000     1
4.0200      1
3.9300      1
0.1550      1
4.1200      1
1.8700      1
0.2200      1
3.1200      1
0.0750      1
2.5800      1
8.9500      1
13.2000     1
0.5100      1
0.5300      1
0.6300      1
1.7200      1
0.7800      1
1.5200      1
0.5200      1
4.6500      1
6.1000      1
0.6800      1
1.0700      1
5.2000      1
0.4275      1
0.4700      1
0.7100      1
0.5250      1
1.4400      1
3.7100      1
0.1800      1
3.0800      1
0.2900      1
0.2400      1
0.4400      1
0.8300      1
0.9800      1
0.4750      1
3.0900      1
0.7400      1
0.6900      1
2.4300      1
0.1300      1
0.9600      1
18.0200     1
0.6580      1
1.3400      1
0.4600      1
2.6000      1
3.8700      1
1.3900      1
0.5900      1
0.2700      1
8.1000      1
14.7500     1
9.5400      1
17.3000     1
18.9000     1
24.0000     1
7.4600      1
0.5995      1
3.9900      1
6.8100      1
8.8100      1
8.9000      1
4.4900      1
22.0000     1
4.1500      1
7.3000      1
18.5000     1
27.5000     1
8.3100      1
6.2100      1
1.8300      1
5.1000      1
3.9000      1
2.0100      1
5.8800      1
0.5275      1
0.4675      1
12.2500     1
9.4000      1
10.3000     1
8.4500      1
6.1500      1
2.4700      1
3.7000      1
18.4000     1
4.4000      1
0.9900      1
2.6500      1
1.2700      1
11.2900     1
4.3100      1
11.5800     1
8.4800      1
8.2000      1
5.5100      1
3.4900      1
2.9900      1
9.1900      1
1.6400      1
9.3500      1
4.0500      1
8.7500      1
23.0000     1
2.4500      1
7.8500      1
25.0000     1
2.6800      1
2.7000      1
1.0400      1
9.8500      1
1.1800      1
15.1000     1
9.0100      1
9.8000      1
4.9900      1
8.6000      1
9.5500      1
2.3500      1
18.2500     1
5.3000      1
10.8000     1
31.5000     1
4.1000      1
7.6500      1
6.4600      1
6.4400      1
7.8000      1
3.8000      1
7.4500      1
7.4200      1
6.0900      1
2.9800      1
Name: count, dtype: int64

In [35]:
df['price_per_sqft']=df['price_per_sqft'].str.split().str[1].str.split('/').str[0].str.replace(",","").astype(float)

In [36]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [38]:
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      31
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
21 Bedrooms      1
20 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [39]:
df['bedRoom'].isnull().sum()

np.int64(108)

In [41]:
df=df[~df['bedRoom'].isnull()]

In [42]:
df.sample(5)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
845,4 Bedroom House for sale in Mayfield Garden,independent,2.95,10926.0,(251 sq.m.) Plot Area,Plot area 300(250.84 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,"Mayfield Garden, Gurgaon, Haryana",4 Floors,East,1 to 5 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Luxurious floor for sale\nLocation - Kibithu v...,"['4 Wardrobe', '8 Fan', '4 Geyser', '1 Microwa...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4.5 out of 5', 'Lifestyle4 out of..."
563,2 Bedroom House for sale in Garhi Harsaru,independent,0.29,3254.0,(83 sq.m.) Plot Area,Plot area 891(82.78 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Garhi Harsaru, Gurgaon, Haryana",0 Floors,West,10+ Year Old,NaN,"Free space avilable ,friendly society,near rai...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
379,3 Bedroom House for sale in Bhim Nagar,independent,0.66,10784.0,(57 sq.m.) Plot Area,Plot area 612(56.86 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Bhim Nagar, Gurgaon, Haryana",2 Floors,NaN,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Looking to buy an independent house in gurgaon...,NaN,"['Water purifier', 'Water Storage', 'Visitor P...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
171,4 Bedroom House for sale in Nirvana Country,unitech deerwood chase,15.00,33333.0,(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,"Jf 67, Nirvana Country, Gurgaon, Haryana",2 Floors,West,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Raheja Mall', ...",A magnificent lifestyle curated for just the e...,"['6 Fan', '7 Light', 'No AC', 'No Bed', 'No Ch...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
495,2 Bedroom House for sale in Arjun Nagar,independent,0.32,7111.0,(42 sq.m.) Built-up Area,Built Up area: 450 (41.81 sq.m.)Carpet area: 3...,2 Bedrooms,3 Bathrooms,1 Balcony,NaN,"Arjun Nagar, Sector 8, Arjun Nagar, Gurgaon, H...",1 Floors,North-East,1 to 5 Year Old,NaN,Best in class property available at arjun naga...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [44]:
df['bedRoom']=df['bedRoom'].str.split().str[0].astype(int)

In [45]:
df['bathroom'].value_counts()

bathroom
4 Bathrooms     228
3 Bathrooms     165
5 Bathrooms     137
2 Bathrooms     114
6 Bathrooms      82
1 Bathroom       65
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      28
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      8
13 Bathrooms      4
18 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: count, dtype: int64

In [46]:
df['bathroom'].isnull().sum()

np.int64(0)

In [47]:
df['bathroom']=df['bathroom'].str.split().str[0].astype(int)

In [49]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [50]:
df['balcony'].value_counts()

balcony
3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: count, dtype: int64

In [58]:
df['balcony']=df['balcony'].str.split().str[0].str.replace('No','0')

In [59]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [60]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Others                                11
Pooja Room,Store Room                            11
Pooja Room,Store Room,Study Room,Servant Room     8
Servant Room,Others                               8
Servant Room,Pooja Room                           8
Pooja Room,Servant Room,Store Room                7
Servant Room,Pooja Room,Store Room                6
Study Room,Servant Room,Pooja Room,Store Room     6
Store Room,Servant Room                           6
Study Room,Pooja Room,Servant Room                5
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Servant Room,Store Room,Pooja Room     4
Servant Room,Store Room,Pooja Room                4
Pooja Room,Study Room,Others                      4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room                4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Store Room,Pooja Room,Servant Room                2
Store Room,Pooja Room,Study Room                  2
Study Room,Pooja Room,Store Room                  2
Servant Room,Study Room,Pooja Room                2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Servant Room,Others                    2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Pooja Room                             2
Study Room,Pooja Room,Store Room,Servant Room     2
Servant Room,Study Room,Store Room,Pooja Room     1
Study Room,Store Room,Pooja Room                  1
Study Room,Store Room                             1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [61]:
df['additionalRoom'].isnull().sum()

np.int64(386)

In [65]:
df['additionalRoom']=df['additionalRoom'].replace(np.nan,'not available')

In [66]:
df['additionalRoom']=df['additionalRoom'].str.lower()

In [67]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [68]:
df['noOfFloor'].value_counts()

noOfFloor
3 Floors     304
2 Floors     288
1 Floors     181
4 Floors     136
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
12 Floors      2
10 Floors      2
11 Floors      2
02 Floors      1
21 Floors      1
27 Floors      1
13 Floors      1
20 Floors      1
41 Floors      1
51 Floors      1
16 Floors      1
33 Floors      1
Name: count, dtype: int64

In [72]:
df[df['noOfFloor'].isnull()]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
23,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,2,"pooja room,servant room,store room","Sector 48 Gurgaon, Gurgaon, Haryana",NaN,East,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Three side open villa in tatvam villa sector-4...,"['1 Chimney', '1 Modular Kitchen', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
51,8 Bedroom House for sale in Palam Vihar,independent,5.60,17284.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8,6,3+,"pooja room,study room,servant room,store room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
203,3 Bedroom House for sale in DLF Phase 3,independent,1.45,26852.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),3,3,1,not available,"DLF Phase 3, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Interested to sell independent house/villa.Pla...,NaN,['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."
252,3 Bedroom House for sale in Ashok Vihar,independent,1.50,10288.0,(135 sq.m.) Plot Area,Plot area 162(135.45 sq.m.)Built Up area: 210 ...,3,3,0,not available,"800 Lane 8 Ashok Vihar Part 1, Ashok Vihar, Gu...",NaN,NaN,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Ground floor and partial first floor built up,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
270,2 Bedroom House for sale in Laxman Vihar Phase 2,independent,4.12,8889.0,(431 sq.m.) Plot Area,Plot area 515(430.61 sq.m.),2,1,3+,not available,"Laxman Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...","Property next to dhanwapur underpass, which is...",[],NaN,NaN
281,3 Bedroom House for sale in New Palam Vihar Ph...,independent,2.50,5472.0,(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),3,2,1,not available,"B-245, New Palam Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",100 mtr from dwarka express way. On 40ft road,NaN,['Park'],NaN
374,4 Bedroom House for sale in Laxman Vihar,independent,0.65,11111.0,(54 sq.m.) Plot Area,Plot area 65(54.35 sq.m.),4,2,2,not available,"Laxman Vihar, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Well maintained two storeyed independent house...,"['1 Wardrobe', '1 Exhaust Fan', '10 Light', '1...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
397,1 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok plots,3.30,26570.0,(115 sq.m.) Plot Area,Plot area 138(115.39 sq.m.),1,1,0,not available,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,NaN,By 2027,"['Iffco chowk metro station', 'Huda city centr...","Close proximity to gold souk , huda city centr...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
417,2 Bedroom House for sale in Bhawani Enclave,independent,1.10,73333.0,(14 sq.m.) Plot Area,Plot area 150(13.94 sq.m.),2,2,1,others,"Bhawani Enclave, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['State bank ATM', 'Shri Multispeciality Hospi...","2 side open, 1 drawing room, 1 shop, 1 small r...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN
560,2 Bedroom House for sale in Jacobpura,jacob pura,0.35,9722.0,(33 sq.m.) Built-up Area,Built Up area: 360 (33.45 sq.m.),2,1,0,not available,"15/3, Jacobpura, Jacobpura, Gurgaon, Haryana",NaN,NaN,10+ Year Old,NaN,Independece house for sale in jacobpura near k...,[],NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
594,6 Bedroom House for sale in DLF Phase 2,independent,13.00,45710.0,(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6,8,3+,"pooja room,servant room,study room,store room","DLF Phase 2, Gurgaon, Haryana",NaN,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...",An impeccable opportunity is here for those wh...,"['1 Water Purifier', '1 Fridge', '1 Sofa', '1 ...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
666,3 Bedroom House for sale in New Colony,independent,6.50,15046.0,(401 sq.m.) Plot Area,Plot area 480(401.34 sq.m.),3,2,3+,not available,"New Colony, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",Old construction house in new colony gurgaon.,[],['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
709,12 Bedroom House for sale in Sector 46 Gurgaon,independent,6.81,36911.0,(171 sq.m.) Plot Area,Plot area 205(171.41 sq.m.),12,14,3+,"servant room,others","Sector 46 Gurgaon, Gurgaon, Haryana",NaN,East,0 to 1 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",204 sqyds newly floor wise building with basem...,"['14 Wardrobe', '15 Fan', '1 Exhaust Fan', '13...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
832,4 Bedroom House for sale in Sector 86 Gurgaon,dlf new town heights,2.47,7718.0,(297 sq.m.) Plot Area,Plot area 3200(297.29 sq.m.)Built Up area: 280...,4,4,3+,"pooja room,servant room","Sector 86 Gurgaon, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",This is beautiful 4 bhk villa in dlf new town ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
855,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,1,not available,"4 Bed And 4 Bathroom, Sector 48 Gurgaon, Gurga...",NaN,NaN,1 to 5 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",360 sq yard 4 bhk residential villa for sale i...,"['4 Bed', '4 Fan', '1 Exhaust Fan', '4 Light',...","['Maintenance Staff', 'Water Storage', 'Separa...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
862,4 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok,10.50,27911.0,(350 sq.m.) Plot Area,Plot area 418(349.5 sq.m.),4,4,2,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,North-East,10+ Year Old,"['Huda city centre metro station', 'New Life C...",Ansal villa for sale 418 sqyd in d block gated...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
865,4 Bedroom House for sale in Sector 26 Gurgaon,independent,4.60,12198.0,(350 sq.m.) Plot Area,Plot area 419(350.34 sq.m.),4,4,3+,not available,"F-5/10, Sector 26 Gurgaon, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...",On the lookout for a spacious house in gurgaon...,[],"['Maintenance Staff', 'Park', 'Visitor Parking...",NaN
1003,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,9.00,21251.0,(521 sq.m.) Plot Area,Plot area 5605(520.72 sq.m.)Built Up area: 520...,4,4,3+,"pooja room,servant room,store room","Sector 66 Gurgaon, Gurgaon, Haryana",NaN,South-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",A lifestyle designed to satiate all your sense...,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1016,12 Bedroom House for sale in Uppals Southend,uppal southend,6.75,290948.0,(22 sq.m.) Plot Area,Plot area 232(21.55 sq.m.),12,12,3+,"pooja room,study room,servant room,others","Uppals Southend, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address... Uppal southend sector 49 s block si...,"['22 Wardrobe', '24 Fan', '1 Exhaust Fan', '33...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [73]:
df['noOfFloor']=df['noOfFloor'].str.split().str[0]

In [75]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [76]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [77]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [78]:
df['facing'].fillna('NA',inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_24476\3692945726.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['facing'].fillna('NA',inplace=True)

0       North-East
1               NA
2             West
3            North
4             West
5             East
6             East
7               NA
8       North-East
9             West
10            West
11           North
12           North
13           North
14            West
15            East
16      South-West
17      North-East
18           South
19           North
20            West
21      North-East
22              NA
23            East
24            East
25      North-East
26      South-East
27      North-East
28      North-West
29              NA
30            East
31           North
32            East
33      North-East
34              NA
35      South-East
36      North-East
37           North
38            East
39           North
40           North
41            East
42      South-East
43      North-West
44            West
45      North-East
46            East
47            East
48           North
49           North
50           South
51      South-West
52      North-East
53      South-East
54            East
55           South
56           North
57              NA
58            East
59            East
73      North-East
74           North
77              NA
78      South-East
92              NA
93            East
103     North-East
104     North-East
114     South-East
119     South-East
120     North-East
121          North
122          North
125           East
126          South
127     South-East
129           East
130           East
131           West
132     North-West
133     North-East
134           East
135     North-West
136     North-West
137     North-West
138     North-West
139     North-East
140          North
141           East
142           East
143     North-West
144           West
145           West
146     South-West
147     North-East
148          North
149           East
150           East
151     North-East
152          North
153           East
154           West
155     North-East
156           East
157          South
158          North
159           West
160     South-East
161     South-East
162          South
163     South-West
164          North
165     North-East
166     North-East
167          South
168           East
169           West
170     South-West
171           West
172     North-East
173     North-East
174           East
175     North-East
176     North-East
177           East
200          North
201           East
202     North-East
203             NA
204           East
205             NA
206             NA
207     North-East
208     North-East
209          North
210     South-West
211     North-West
212             NA
213             NA
214     North-East
215     North-East
216     South-West
217           East
218             NA
219             NA
220     South-East
221             NA
222           East
223             NA
224             NA
225          South
226             NA
227     North-East
228          North
229             NA
230             NA
231             NA
232           East
233             NA
234             NA
235             NA
236             NA
237             NA
238             NA
239             NA
240             NA
241             NA
242             NA
243     North-East
244             NA
245             NA
246           West
247          South
248     North-East
249          South
250           East
251     North-East
252             NA
253             NA
254             NA
255           East
256           East
257     North-East
258     South-East
259           East
260           East
261             NA
262             NA
263          North
264     North-East
265             NA
266          North
267             NA
268             NA
269             NA
270             NA
271             NA
272             NA
273             NA
274             NA
275             NA
276             NA
277           East
278     South-West
279             NA
280             NA
281             NA
282           East
283             NA
284          South
285           East
286           East
287          North
288           East
289             NA
290             NA
291             NA
292             NA
293             NA
294             NA
297             NA
298             NA
299             NA
300             NA
301           East
302             NA
303             NA
304             NA
305          South
306             NA
307     North-East
309     South-East
310           East
311          North
314             NA
315     North-East
316           East
317          North
318             NA
320          North
321             NA
322             NA
323             NA
324     North-West
332             NA
333          North
334             NA
335             NA
336             NA
337             NA
338     South-East
339             NA
340             NA
341             NA
342             NA
343             NA
344             NA
345             NA
346             NA
347             NA
348     North-East
349             NA
350             NA
351             NA
352             NA
357             NA
370             NA
374             NA
375             NA
376     North-East
377             NA
378             NA
379             NA
380          North
381             NA
382     South-West
383     South-East
384          North
385             NA
386             NA
387           East
388             NA
389     South-East
390     North-East
391             NA
392             NA
393             NA
394           East
395           East
396     North-East
397             NA
398             NA
399           West
400     South-East
401             NA
403             NA
404           West
405             NA
406             NA
407     North-East
408             NA
409             NA
410          South
411             NA
412           East
413          North
414           West
415             NA
416             NA
417             NA
418             NA
419             NA
420          North
421             NA
422             NA
423     North-East
424             NA
425             NA
426             NA
427             NA
428           East
429           West
430             NA
432          North
433             NA
434             NA
435             NA
436           East
437     South-West
438           West
439             NA
440             NA
441     South-East
442             NA
443             NA
444          North
445     South-East
446             NA
447             NA
448     North-West
449     North-West
450             NA
451          North
452     North-East
453             NA
454             NA
455           East
456     North-East
457             NA
458             NA
459             NA
460             NA
461           East
462             NA
463     South-West
464          North
465           East
466     South-East
467           East
468           West
469             NA
470             NA
471             NA
472           West
473             NA
474           East
475     North-West
476             NA
477          North
478          South
479     North-East
480             NA
481             NA
482     North-West
483             NA
484     North-West
485     North-East
486             NA
487     North-East
488     South-East
489     North-West
490             NA
491          North
492     North-East
493             NA
495     North-East
496           East
497          South
498     South-East
499             NA
500             NA
501             NA
502           East
503     North-East
504           East
505             NA
506             NA
507     North-East
508          South
509          South
510             NA
511           West
512          North
513          South
514          North
515             NA
516             NA
517             NA
518             NA
519             NA
520     North-West
521             NA
522             NA
523             NA
524             NA
525             NA
526             NA
527             NA
528           East
529          North
530             NA
531     North-East
532             NA
533           East
534             NA
535           East
536             NA
537           East
538             NA
539             NA
540          North
541             NA
542             NA
543          North
544             NA
545             NA
546             NA
547           East
548             NA
549             NA
550          North
551     North-East
552          North
553           East
554             NA
555     North-East
556             NA
557             NA
558             NA
559     South-East
560             NA
561           West
562             NA
563           West
564          North
565     South-West
566     North-East
567             NA
568     North-East
570             NA
571     South-East
572          South
573             NA
574           East
575     North-East
576          South
577          South
578             NA
579             NA
580             NA
581           East
582           East
583             NA
584             NA
585             NA
586             NA
587          North
588             NA
589             NA
590          South
591             NA
592             NA
593     North-East
594             NA
596     North-East
597             NA
598           East
599           West
600          North
601           East
602             NA
603             NA
604             NA
605     South-West
606             NA
607             NA
608             NA
609             NA
610          North
611             NA
612          North
613             NA
614             NA
615             NA
616             NA
617             NA
618             NA
619             NA
620             NA
621             NA
622     North-East
623     North-West
624             NA
625             NA
626           East
627           East
628     North-East
629             NA
630             NA
631     North-East
632             NA
633             NA
634           East
635     North-East
636             NA
637          North
638             NA
639           East
640             NA
641             NA
642             NA
643             NA
644             NA
645             NA
646          North
647             NA
648             NA
649     North-West
650             NA
651     South-East
652           East
653             NA
654             NA
655     South-East
656             NA
657           East
658     North-West
659           East
660     North-East
661           West
662           East
663           East
664     North-West
665             NA
666             NA
667     North-East
669     North-East
670             NA
671             NA
672           East
673             NA
674           East
675     South-West
676           West
677             NA
678             NA
679          North
680           West
681     South-East
682     North-East
683          North
684             NA
685           East
686           West
687             NA
688          North
689          North
690             NA
691             NA
692           East
693           East
694           East
695     North-East
696          North
697           East
698          North
699           West
700     North-East
701             NA
702     North-East
703             NA
704     North-West
705           East
706           West
707           West
708     North-East
709           East
710           East
711             NA
712          South
713             NA
714             NA
715           East
716           East
717     South-East
718           West
719     North-West
720             NA
721          South
722     North-East
723     North-West
724             NA
725     North-East
726           East
727           East
728           East
729     North-East
730           East
731           East
732     North-West
733           East
734             NA
735     North-East
736             NA
737     North-West
738           East
739           East
740          North
741     North-East
742          North
743          North
744           East
745          North
746     North-East
747     North-East
748           West
749     North-East
750     North-East
751     North-East
752             NA
753             NA
754           East
755          South
756           East
757     North-West
758     North-West
759           West
760     North-East
761             NA
762          North
763             NA
764          North
765     North-West
766             NA
767           East
768     South-West
769           East
770     North-East
771           East
772             NA
773          North
774             NA
775     North-East
776     North-East
777           East
778     North-East
779     North-East
780           East
781           East
782           East
783     South-East
784             NA
785           East
786           West
787           West
788     North-East
789     North-West
790          South
791     South-East
792          North
793           East
794           West
795           East
796          North
797           East
798           West
799           East
800     North-East
801     North-East
802           East
803     North-East
804     North-East
805     South-West
806           East
807           West
808          North
809     North-East
810           East
811     North-East
812          North
813           East
814     North-East
815             NA
816     North-East
817     North-East
818           West
819          North
832           West
833     North-East
834          South
835           East
836     North-West
837           East
838     North-East
839          North
840             NA
841             NA
842     South-East
843           West
844     North-East
845           East
846          North
847           East
848           East
849           East
850     North-West
851     North-East
852     North-East
853             NA
854          North
855             NA
856           East
857             NA
858          North
859     North-East
860          North
861           East
862     North-East
863           East
864             NA
865             NA
866             NA
867             NA
868     North-East
869     North-West
870     South-West
872           West
873           West
874           East
875     North-East
876     North-East
877           West
878           East
879     North-East
880     North-East
881             NA
882          North
883          North
884     North-West
885     North-East
886           East
887     North-West
888          North
889           East
890     North-East
891     South-East
892           West
893     North-East
895           West
896           East
897     North-East
898     North-West
899             NA
900     North-West
901             NA
902          North
903     South-West
904             NA
905     North-East
906     North-West
907           East
908           East
909          North
910          North
911     South-East
912          South
913           West
914          South
915     North-East
916          North
917           East
918           East
919           East
920     North-East
921           East
922     North-East
923     North-East
924     South-West
925     North-East
926           West
927           East
928          North
929     North-East
930           West
931           West
932     North-East
933           East
934     South-West
935          South
936     North-East
937             NA
938          North
939             NA
940           East
941           East
942     North-East
943     North-East
944           West
945             NA
946     North-East
947     North-East
948          North
949           East
950     North-East
951           East
952             NA
953     North-East
954           West
955           West
956     North-West
957           West
958     North-East
959          North
960           East
961           East
962     North-East
963           West
964           East
965     North-East
966     North-East
967           West
968           East
969             NA
970           East
971          South
972     North-East
973     North-East
974     North-East
975     North-East
976     North-East
977          North
978          South
979     South-West
980          North
981     North-East
982          North
983           East
984           East
985           East
986          North
987           East
988           East
989           East
990          North
991          North
992          North
993          North
994          North
995     South-East
996           East
997          North
998     North-East
999     North-East
1000    North-West
1001          East
1002    North-East
1003    South-West
1004          West
1005          East
1006            NA
1007         South
1008          West
1009          West
1010            NA
1011            NA
1012         North
1013          West
1014    South-East
1015          West
1016          West
1017          East
1018         North
1019    North-East
1020         North
1021          West
1022            NA
1023          West
1024         North
1025    North-East
1026          East
1027         North
1028          East
1029          West
1030         North
1031          West
1032          East
1033          East
1034    North-East
1035            NA
1036         North
1037    North-East
1038    North-East
1039          East
1040          East
1041    North-East
1042    South-East
1043    North-East
1044          West
1045    North-East
1046    North-East
1047         North
1048    North-East
1049          West
1050          West
1051          East
1052            NA
1053          East
1054          East
1055          East
1056          East
1057    North-West
1058          East
1059         North
1060    South-East
1061         South
1062            NA
1063          East
1064            NA
1065          West
1066    North-East
1067            NA
1068          West
1069          East
1070         North
1071            NA
1072          East
1073          East
1074          East
1075    North-East
1076    North-East
1077    South-East
1078    North-West
1079    South-West
1080    South-West
1081    North-West
1082    South-East
1083    North-East
1084    North-West
1085            NA
1086    North-East
1087         North
1088          East
1089          West
1090            NA
Name: facing, dtype: str

In [79]:
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

In [80]:
df.insert(loc=1,column='property_type',value='house')

In [81]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [82]:
df.info()

<class 'pandas.DataFrame'>
Index: 964 entries, 0 to 1090
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    str
 1   property_type    964 non-null    str
 2   society          964 non-null    str
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     964 non-null    str
 7   bedRoom          964 non-null    int64
 8   bathroom         964 non-null    int64
 9   balcony          964 non-null    object
 10  additionalRoom   964 non-null    str
 11  address          959 non-null    str
 12  floorNum         945 non-null    object
 13  facing           661 non-null    str
 14  agePossession    964 non-null    str
 15  nearbyLocations  848 non-null    str
 16  description      964 non-null    str
 17  furnishDetails   729 non-null    str
 18  features         662 non-null    str
 19  rating           843 non-null    str
dtypes: float64(3), int64(2), object(2), str(13)
memory usage: 1.7+ MB

In [83]:
df.to_csv('house_cleaned.csv',index=False)

In [84]:
df.shape

(964, 20)