In [55]:
import pandas as pd
import numpy as np

In [56]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [57]:
df=pd.read_csv('gurugram_properties.csv')
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   str
 1   property_type    3961 non-null   str
 2   society          3960 non-null   str
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   str
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   str
 10  additionalRoom   3961 non-null   str
 11  address          3950 non-null   str
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   str
 14  agePossession    3960 non-null   str
 15  nearbyLocations  3754 non-null   str
 16  description      3961 non-null   str
 17  furnishDetails   2929 non-null   str
 18  features         3252 non-null   str
 19  rating           3511 non-null   str
dtypes: float64(4), int64(2), str(14)
memory usage: 6.9 MB

In [59]:
df.head(1)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [60]:
df.insert(loc=3, column='sector',value=df['property_name'].str.split("in").str.get(1).str.replace("Gurgaon","").str.strip())

In [61]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,Krishna Colony,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,Ashok Vihar,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,Sohna,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,Sector 61,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,Sector 92,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [62]:
df['sector']=df['sector'].str.lower()

In [63]:
df.head(1)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,krishna colony,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [64]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [65]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [66]:
df['sector'].value_counts()

sector
sohna road                                                   163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 90                                                     90
sector 65                                                     90
sector 109                                                    88
sector 79                                                     80
sector 104                                                    73
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 50                                                     65
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 48                                                     56
sector 2                                                      55
sector 70a                                                    54
sector 37c                                                    53
sector 43                                                     53
sector 70                                                     53
sector-33 sohna road                                          51
sector 84                                                     51
sector 26                                                     50
sector 49                                                     48
sector 67                                                     48
sector 28                                                     47
sector 66                                                     46
sector 103                                                    45
sector 113                                                    43
sector 25                                                     43
sector 61                                                     42
sector 82                                                     42
sector 7                                                      39
sector 106                                                    38
sector 4                                                      36
sector 99a                                                    32
sector 54                                                     31
sector 68                                                     30
sector 12                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 57                                                     24
sector 24                                                     24
sector 112                                                    24
sector 33                                                     23
sector 88a                                                    23
sector 14                                                     23
sector 105                                                    23
sector 67a                                                    22
sector 111                                                    22
sector 11                                                     21
sector 3                                                      20
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 47                                                     19
sector 63a                                                    18
gwal pahari                                                   18
sector 74                                                     18
sector 62                                                     17
sector 91                                                     17
sector 99                                                     16
sector 110                                                    16
sector 63                                                     15
sector 60                                                     15
sector 52                                                     14
sector 53                                                     14
sector 1 manesar                                              14
sector 55                                                     14
sector 76                                                     14
sector 36a                                                    13
sector 4 phase 2                                              13
sector 6                                                      13
sector 9                                                      13
sector 46                                                     13
sector 93                                                     12
sohna road road                                               12
sector 38                                                     12
sector 39                                                     12
sector 31                                                     12
sector 3 phase 3 extension                                    11
sector 41                                                     11
sector 9a                                                     11
sector 1a manesar                                             10
sector 13                                                     10
sector 95a                                                     9
sector 3 phase 2                                               9
sector 45                                                      9
manesar                                                        9
dwarka expressway                                              8
sector 10a                                                     8
sector 59                                                      8
sector 89 a                                                    8
sector 2 extension                                             8
sector 40                                                      8
c block sector 43                                              8
sector 23                                                      8
sector 8                                                       8
sector 17                                                      8
sector 36 sohna road                                           7
sector 51                                                      7
sector 58                                                      7
sector 1                                                       6
sector 21                                                      6
sector 5                                                       6
new sector 2                                                   5
sector 30                                                      5
sector 80                                                      5
sector 23a                                                     5
sector 36                                                      4
sector 12a                                                     4
new                                                            4
sector 3a                                                      4
sector 88b                                                     3
sector 73                                                      3
sector 15                                                      3
sector 110 a                                                   3
patel nagar                                                    3
b block sector 43                                              3
sector 17a                                                     3
maruti kunj                                                    3
sector 17b                                                     3
a block sector 43                                              3
sector 27                                                      3
block a sector 21                                              2
sector 15 part 1                                               2
bhawani enclave                                                2
iffco chowk                                                    2
golf course road                                               2
sector-11 sohna road                                           2
ambience island                                                2
lajpat nagar                                                   2
sector 32                                                      2
sector-2 sohna road                                            2
shanti nagar                                                   2
sushant lok                                                    2
faridabad road                                                 2
samaspur                                                       2
sispal vihar                                                   2
golf course ext road                                           2
shankar vihar                                                  2
new sector 2 phase 2                                           2
new sector 2 phase 1                                           2
sector 15 part 2                                               2
nars                                                           2
hira nagar                                                     2
mohan nagar                                                    2
daulatabad                                                     2
new basti                                                      2
surat nagar phase 2                                            2
surat nagar                                                    2
west sector 13                                                 2
sheetla colony                                                 2
farukhnagar                                                    2
acharya puri                                                   2
pratap nagar                                                   2
manohar nagar                                                  2
, delhi ncr                                                    2
sohna road  road                                               2
rajiv chowk                                                    2
mayfield garden                                                2
rosewood                                                       2
bissar                                                         2
sector-7 hous                                                  1
rajiv colony                                                   1
garauli kalan                                                  1
near sector 1 market                                           1
kanahi                                                         1
heritage city                                                  1
sai kunj                                                       1
sultanpur                                                      1
civil l                                                        1
sector 7, sector 7                                             1
near pataudi chowk                                             1
cyber city                                                     1
ats marigold                                                   1
sector 37a                                                     1
carterpuri village                                             1
sector-5 sohna road                                            1
sector 5 chowk                                                 1
old delhi road, opp sector-14                                  1
sector 50 pocket h                                             1
sector-35 sohna road                                           1
saroop garden sector 105                                       1
sector 4 urban estate                                          1
bptp                                                           1
godrej aria , sector 79 ,                                      1
sector 21a faridabad                                           1
hsiidc plot sector 1 manesar                                   1
sector 17c                                                     1
gopal nagar, garhi ghasita, sonipat                            1
jat colony,fazilpur/taj nagar road                             1
kheri                                                          1
sector 9b                                                      1
bhora kalan                                                    1
near nand hospital                                             1
sector 3 phase i                                               1
block h sector 3 phase iii extension                           1
khandsa                                                        1
urban estate, sector 5                                         1
near khandsa road                                              1
part 3 sector 5                                                1
lucknow                                                        1
pataudi road                                                   1
vir nagar                                                      1
hno 13 sagar enclave sura                                      1
ram nagar                                                      1
block g sector-57                                              1
om nagar                                                       1
anand garden, sector-105                                       1
tekchand nagar                                                 1
sector 3 phase 3                                               1
ansal's sector 2                                               1
sector 12 near sadar bazar                                     1
shivji park colony                                             1
udyog vihar phase 1                                            1
mahasector 11, rajendra place                                  1
rattan garden                                                  1
sadar bazar                                                    1
naharpur rupa                                                  1
sector 4, railway road,                                        1
sector-5 sheetla colony                                        1
damdma                                                         1
new sector 7                                                   1
mahavir pura                                                   1
sector 37b                                                     1
g block dlf city phase 1                                       1
park view                                                      1
ravi nager basai road                                          1
begampur khatola                                               1
dhankot                                                        1
devi lal colony gali no 12 gurgaon nr omkar public school      1
alipur                                                         1
saraswati enclave                                              1
sec 3 bhim vihar part 1 bhimgher kheri                         1
near euro                                                      1
bhimgarh kheri phase 3                                         1
huda sector 28                                                 1
laxmna vihar, phase 2                                          1
b1 block sector 57                                             1
sector 42                                                      1
south city                                                     1
v block sector 24                                              1
Name: count, dtype: int64

In [67]:
a=df['sector'].value_counts()[df['sector'].value_counts()>=3]

In [68]:
df=df[df['sector'].isin(a.index)]

In [69]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 90                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 89                      56
sector 48                      56
sector 2                       55
sector 70a                     54
sector 37c                     53
sector 43                      53
sector 70                      53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 57                      24
sector 24                      24
sector 112                     24
sector 33                      23
sector 88a                     23
sector 14                      23
sector 105                     23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 3                       20
sector 82a                     20
sector 22                      20
sector 78                      19
sector 47                      19
sector 63a                     18
gwal pahari                    18
sector 74                      18
sector 62                      17
sector 91                      17
sector 99                      16
sector 110                     16
sector 63                      15
sector 60                      15
sector 52                      14
sector 53                      14
sector 1 manesar               14
sector 55                      14
sector 76                      14
sector 36a                     13
sector 4 phase 2               13
sector 6                       13
sector 9                       13
sector 46                      13
sector 93                      12
sohna road road                12
sector 38                      12
sector 39                      12
sector 31                      12
sector 3 phase 3 extension     11
sector 41                      11
sector 9a                      11
sector 1a manesar              10
sector 13                      10
sector 95a                      9
sector 3 phase 2                9
sector 45                       9
manesar                         9
dwarka expressway               8
sector 10a                      8
sector 59                       8
sector 89 a                     8
sector 2 extension              8
sector 40                       8
c block sector 43               8
sector 23                       8
sector 8                        8
sector 17                       8
sector 36 sohna road            7
sector 51                       7
sector 58                       7
sector 1                        6
sector 21                       6
sector 5                        6
new sector 2                    5
sector 30                       5
sector 80                       5
sector 23a                      5
sector 36                       4
sector 12a                      4
new                             4
sector 3a                       4
sector 88b                      3
sector 73                       3
sector 15                       3
sector 110 a                    3
patel nagar                     3
b block sector 43               3
sector 17a                      3
maruti kunj                     3
sector 17b                      3
a block sector 43               3
sector 27                       3
Name: count, dtype: int64

In [70]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')
df['sector'] = df['sector'].str.replace('sector 37d','sector 37')
df['sector'] = df['sector'].str.replace('sector 70a','sector 70')
df['sector'] = df['sector'].str.replace('sector 37c','sector 37')
df['sector'] = df['sector'].str.replace('sector 99a','sector 99')
df['sector'] = df['sector'].str.replace('sector 67a','sector 67')
df['sector'] = df['sector'].str.replace('sector 82a','sector 82')
df['sector'] = df['sector'].str.replace('sector 63a','sector 63')
df['sector'] = df['sector'].str.replace('sector 36a','sector 36')
df['sector'] = df['sector'].str.replace('sector 9a','sector 9')
df['sector'] = df['sector'].str.replace('sector 10a','sector 10')
df['sector'] = df['sector'].str.replace('sector 88b','sector 88')
df['sector'] = df['sector'].str.replace('sector 17a','sector 17')
df['sector'] = df['sector'].str.replace('sector 17b','sector 17')
df['sector'] = df['sector'].str.replace('','')

In [71]:
df['sector'].value_counts()

sector
sohna road                    163
sector 37                     121
sector 102                    113
sector 85                     110
sector 70                     107
sector 92                     104
sector 69                      94
sector 81                      90
sector 90                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 33                      74
sector 104                     73
sector 67                      70
sector 83                      69
sector 43                      67
sector 86                      67
sector 95                      66
sector 50                      65
sector 89                      64
sector 2                       63
sector 82                      62
sector 107                     60
sector 108                     59
sector 56                      57
sector 48                      56
sector 84                      51
sector 26                      50
sector 4                       49
sector 99                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 7                       39
sector 106                     38
sector 12                      37
manesar                        33
sector 63                      33
sector 54                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 3                       24
sector 36                      24
sector 57                      24
sector 9                       24
sector 24                      24
sector 112                     24
sector 88a                     23
sector 14                      23
sector 105                     23
sector 111                     22
sector 11                      21
sector 22                      20
sector 78                      19
sector 47                      19
sector 110                     19
gwal pahari                    18
sector 74                      18
sector 62                      17
sector 91                      17
sector 60                      15
sector 52                      14
sector 53                      14
sector 55                      14
sector 76                      14
sector 17                      14
sector 23                      13
sector 6                       13
sector 46                      13
sector 93                      12
sohna road road                12
sector 38                      12
sector 39                      12
sector 31                      12
sector 3 phase 3 extension     11
sector 41                      11
sector 13                      10
sector 3 phase 2                9
sector 45                       9
dwarka expressway               8
sector 10                       8
sector 59                       8
sector 40                       8
sector 8                        8
sector 51                       7
sector 58                       7
sector 1                        6
sector 15                       6
sector 21                       6
sector 5                        6
new sector 2                    5
sector 30                       5
sector 80                       5
new                             4
sector 88                       3
sector 73                       3
sector 27                       3
Name: count, dtype: int64

In [72]:
df[df['sector']=='new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2045,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2803,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2895,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2960,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [74]:
df.loc[2045,'sector'] = 'sector 76'
df.loc[2803,'sector'] = 'sector 37'
df.loc[2895,'sector'] = 'sector 90'
df.loc[2960,'sector'] = 'sector 92'

In [75]:
df['sector'].value_counts()

sector
sohna road                    163
sector 37                     122
sector 102                    113
sector 85                     110
sector 70                     107
sector 92                     105
sector 69                      94
sector 90                      91
sector 81                      90
sector 65                      90
sector 109                     88
sector 79                      80
sector 33                      74
sector 104                     73
sector 67                      70
sector 83                      69
sector 43                      67
sector 86                      67
sector 95                      66
sector 50                      65
sector 89                      64
sector 2                       63
sector 82                      62
sector 107                     60
sector 108                     59
sector 56                      57
sector 48                      56
sector 84                      51
sector 26                      50
sector 4                       49
sector 99                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 7                       39
sector 106                     38
sector 12                      37
manesar                        33
sector 63                      33
sector 54                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 3                       24
sector 36                      24
sector 57                      24
sector 9                       24
sector 24                      24
sector 112                     24
sector 88a                     23
sector 14                      23
sector 105                     23
sector 111                     22
sector 11                      21
sector 22                      20
sector 78                      19
sector 47                      19
sector 110                     19
gwal pahari                    18
sector 74                      18
sector 62                      17
sector 91                      17
sector 60                      15
sector 76                      15
sector 52                      14
sector 53                      14
sector 55                      14
sector 17                      14
sector 23                      13
sector 6                       13
sector 46                      13
sector 93                      12
sohna road road                12
sector 38                      12
sector 39                      12
sector 31                      12
sector 3 phase 3 extension     11
sector 41                      11
sector 13                      10
sector 3 phase 2                9
sector 45                       9
dwarka expressway               8
sector 10                       8
sector 59                       8
sector 40                       8
sector 8                        8
sector 51                       7
sector 58                       7
sector 1                        6
sector 15                       6
sector 21                       6
sector 5                        6
new sector 2                    5
sector 30                       5
sector 80                       5
sector 88                       3
sector 73                       3
sector 27                       3
Name: count, dtype: int64

In [77]:
df[df['sector']=='new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
30,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.600,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
88,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.285,3166.0,900.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
2842,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.220,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3168,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.340,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3274,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.000,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [78]:
df.loc[[30,88,1486,2842,3168,3274],'sector'] = 'sector 110'

In [79]:
df.shape

(3803, 21)

In [80]:
df.duplicated().sum()

np.int64(0)

In [81]:
df.head(1)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,sector 7,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [82]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description'],inplace=True)

In [83]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
2376,flat,m3m woodshire,sector 107,1.01,7394.0,1366.0,Super Built up area 1366(126.91 sq.m.)Built Up...,2,2,3+,others,11.0,NaN,0 to 1 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",NaN,"['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Green Area4.5 out of 5', 'Construction5 out ..."
2921,flat,prime habitat,sector 99,0.32,4657.0,687.0,Super Built up area 687(63.82 sq.m.)Built Up a...,2,2,1,not available,7.0,NaN,1 to 5 Year Old,"['The Hive Mall', 'Omaxe Gurgaon Mall', 'Gurug...","['1 Fan', '1 Exhaust Fan', '1 Light', '1 Modul...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Safety3 out of 5', 'Lifestyle3 out of 5', 'E..."
3785,house,unitech palms south city 1,sector 41,9.35,28858.0,3240.0,Plot area 3240(301.01 sq.m.)Built Up area: 750...,10,10,3+,"servant room,study room",4.0,North-East,5 to 10 Year Old,"['Huda city centre metro station', 'Hdfc ATM',...","['6 Fan', '10 Light', '5 AC', '1 Modular Kitch...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
3036,house,independent,sector 25,9.00,33333.0,2700.0,Plot area 300(250.84 sq.m.),5,5,3,"pooja room,study room,servant room,store room",3.0,North,10+ Year Old,"['Vodafone belvedere towers metro station', 'D...",NaN,"['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3884,house,independent,sector 25,9.90,29333.0,3375.0,Plot area 375(313.55 sq.m.),5,5,2,pooja room,2.0,South-East,5 to 10 Year Old,"['Vodafone belvedere towers metro station', 'D...","['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [84]:
df.to_csv('gurugram_properties_cleaned_v1.csv',index=False)