In [1]:
import numpy as numpy
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df=pd.read_csv('flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
86,3 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Puri The Aravallis,3.87 Crore,"₹ 17,200/sq.ft.",Super Built up area 2250(209.03 sq.m.)Carpet a...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"3bhk, Sector 61 Gurgaon, Gurgaon, Haryana",21st of 41 Floors,East,Jan 2027,"['Sector 55-56 Metro Station', 'Hong Kong Baza...",One of top location for 3bhk + s unit.,"['1 Fan', '1 Light', '1 AC', 'No Bed', 'No Chi...","['Intercom Facility', 'Lift(s)', 'High Ceiling...",NaN,N68643454
2152,3 BHK Flat in Sohna,https://www.99acres.com/3-bhk-bedroom-apartmen...,Central Park Flower Valley,1.2 Crore,"₹ 6,742/sq.ft.",Built Up area: 1780 (165.37 sq.m.),3 Bedrooms,3 Bathrooms,No Balcony,NaN,"Sohna, Sohna, Gurgaon, Haryana",11st of 12 Floors,NaN,undefined,NaN,3bhk multistorey apartment for resale in centr...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5...",X67181112
732,4 BHK Flat in Sector 82A Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,DLF The Primus3.9 ★,2.95 Crore,"₹ 11,451/sq.ft.",Super Built up area 2576(239.32 sq.m.)Carpet a...,4 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,"10th Dlf Primus Sector 82a Gurgaon, Sector 82A...",10th of 32 Floors,North-East,1 to 5 Year Old,"['Sapphire 83', 'NH 48', 'Cambridge Montessori...",This is 4bhk plus apartment for sale key in ha...,"['1 Water Purifier', '7 Fan', '1 Fridge', '4 G...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4.5 out ...",U70012350
222,3 BHK Flat in Sector 65 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,M3M Heights,2.79 Crore,"₹ 14,168/sq.ft.",Super Built up area 1828(169.83 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Mid Floor, Sector 65 Gurgaon, Gurgaon, Haryana",26th of 47 Floors,East,Within 6 months,"['Rapid Metro Sector 56', 'M3m 65th Avenue Mal...","Awesome views,running balcony, pool facing, mi...",[],"['Intercom Facility', 'Lift(s)', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ...",J68308392
1718,3 BHK Flat in Sector 84 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Antriksh Heights3.7 ★,85 Lac,"₹ 4,927/sq.ft.",Super Built up area 1725(160.26 sq.m.),3 Bedrooms,3 Bathrooms,3+ Balconies,Study Room,"Antriksh Heights, Sector 84 Gurgaon, Gurgaon, ...",10th of 19 Floors,North,1 to 5 Year Old,"['Old Bengali Market', 'MatriKiran High School...",Middle floor unit for sale for visit or detail...,[],"['Power Back-up', 'Lift(s)', 'High Ceiling Hei...","['Green Area4.5 out of 5', 'Construction3.5 ou...",C69994078

In [4]:
df.shape

(3028, 20)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   str
 1   link             3028 non-null   str
 2   society          3027 non-null   str
 3   price            3008 non-null   str
 4   area             3015 non-null   str
 5   areaWithType     3009 non-null   str
 6   bedRoom          3009 non-null   str
 7   bathroom         3009 non-null   str
 8   balcony          3009 non-null   str
 9   additionalRoom   1695 non-null   str
 10  address          3003 non-null   str
 11  floorNum         3007 non-null   str
 12  facing           2128 non-null   str
 13  agePossession    3008 non-null   str
 14  nearbyLocations  2914 non-null   str
 15  description      3009 non-null   str
 16  furnishDetails   2204 non-null   str
 17  features         2595 non-null   str
 18  rating           2677 non-null   str
 19  property_id      3009 non-null   str
dtypes: str(20)
memory usage: 5.8 MB

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

In [8]:
df.drop(columns=['link','property_id'],inplace=True)

In [9]:
df.head(1)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [10]:
df.rename(columns={'area':'price_per_sqft'},inplace=True)

In [11]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Orchard                                  32
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
BPTP Terra3.8 ★                                      25
Emaar Gurgaon Greens4.1 ★                            25
DLF New Town Heights 13.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Experion The Heartsong3.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Bestech Park View Residency3.9 ★                     23
ATS Triumph3.9 ★                                     22
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Supertech Araville                                   19
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Sobha City                                           18
CHD Avenue 713.6 ★                                   18
Ambience Creacions                                   18
Indiabulls Centrum Park3.7 ★                         18
ATS Tourmaline3.9 ★                                  18
Mapsko Mount Ville4.1 ★                              18
M3M Golfestate4.4 ★                                  17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             17
M3M Skywalk                                          17
Conscient Heritage Max4.3 ★                          17
Godrej Summit3.7 ★                                   17
HCBS Sports Ville3.6 ★                               16
Godrej Oasis3.9 ★                                    16
Umang Monsoon Breeze                                 16
M3M Merlin3.7 ★                                      16
Bestech Park View Grand Spa4.3 ★                     16
Ansal Heights 86                                     15
Emaar MGF The Palm Drive4.1 ★                        15
Corona Optus3.9 ★                                    15
DLF The Primus3.9 ★                                  14
Umang Winter Hills3.9 ★                              14
Ramsons Kshitij3.7 ★                                 14
MVN Athens3.7 ★                                      14
Indiabulls Enigma                                    14
Ireo Victory Valley4.1 ★                             14
The Close North4.0 ★                                 14
Orchid Petals4.1 ★                                   14
Ireo Skyon4.0 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Imperia The Esfera                                   14
Central Park Flower Valley                           13
Bestech Park View Ananda4.2 ★                        13
Puri Emerald Bay3.7 ★                                13
Ireo The Corridors                                   13
Breez Global Hill View                               11
M3M Soulitude                                        11
Godrej Aria3.8 ★                                     11
Raheja Vedaanta3.6 ★                                 11
Adani M2K Oyster Grande3.9 ★                         11
TARC Maceo3.8 ★                                      11
SBTL Caladium                                        11
Alpha Corp GurgaonOne 844.0 ★                        11
DLF The Skycourt4.2 ★                                11
ILD Greens4.1 ★                                      10
Godrej Air                                           10
Pivotal Devaan                                       10
Breez Global Heights4.2 ★                            10
Emaar MGF Palm Hills4.0 ★                            10
Pyramid Urban Homes 2                                10
Zara Aavaas                                          10
Ramprastha The Edge Towers3.5 ★                      10
DLF New Town Heights 24.0 ★                          10
ATS Kocoon                                           10
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
Signature Global Synera3.4 ★                         10
Pareena Mi Casa                                       9
Parsvnath Green Ville3.9 ★                            9
Bestech Park View Sanskruti4.2 ★                      9
AIPL The Peaceful Homes3.9 ★                          9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
Bestech Altura                                        8
M3M Skycity                                           8
GLS Avenue 51                                         8
Assotech Blith                                        8
M3M Capital                                           8
Emaar Digihomes                                       8
Orris Aster Court Premier                             8
The Lions CGHS                                        8
Tulip Ivory3.5 ★                                      8
Vatika Lifestyle Homes3.8 ★                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
Birla Navya                                           8
Emaar Imperial Gardens3.8 ★                           7
Mapsko Casa Bella3.8 ★                                7
Sare Crescent Parc Royal Greens Phase 1               7
Signature Global City                                 7
Ansal Housing Highland Park                           7
Trisara Our Homes 3                                   7
AIPL Zen Residences                                   7
Orris Carnation Residency3.7 ★                        7
Sare Green ParC Phase 3                               7
Ireo The Grand Arch4.0 ★                              7
Signature Andour Heights3.8 ★                         7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Supertech Hues                                        6
Ashiana Mulberry                                      6
DLF Regency Park 13.6 ★                               6
Signature Global City 63A                             6
Signature The Roselia3.6 ★                            6
Greenopolis                                           6
Hero Homes                                            6
Suncity Vatsal Valley                                 6
Sidhartha NCR One Phase 14.2 ★                        6
Signature Global Park 4                               6
HSIIDC Sidco Aravali                                  6
Bestech Park View City4.1 ★                           6
Mapsko Royale Ville3.7 ★                              6
Kiran Residency                                       6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
Pyramid Urban                                         6
M3M Sierra 68                                         6
Pioneer Araya3.8 ★                                    6
BPTP Astaire Gardens3.7 ★                             6
Shapoorji Pallonji Joyville Gurugram                  6
Apna Enclave                                          5
Signature Global City 81                              5
Godrej Habitat                                        5
Silverglades The Melia                                5
Pareena Laxmi Apartments3.6 ★                         5
Satya The Hermitage3.5 ★                              5
Central Park Flower Valley Aqua Front Towers          5
Green Court3.7 ★                                      5
Ashiana Anmol3.5 ★                                    5
Signature Global the Millennia                        5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Central Park Resorts4.4 ★                             5
DLF Regency Park 24.0 ★                               5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Emaar MGF Emerald Estate3.8 ★                         5
Vatika City Homes3.9 ★                                5
DLF Park Place4.1 ★                                   5
Ireo Uptown4.1 ★                                      5
Signature Global Grand IVA3.9 ★                       5
Adani Brahma Samsara Vilasa                           5
Signature Global City 37D Ph 2                        5
ATS Marigold                                          5
Conscient Elevate                                     5
Krisumi Waterfall Residences                          5
Essel Towers                                          5
Vatika Sovereign Park                                 5
Ramprastha Skyz                                       4
Signature The Serenas                                 4
DLF New Town Heights3.7 ★                             4
Lotus Homz4.0 ★                                       4
Unitech Vistas                                        4
ILD Grand                                             4
Global Hill View                                      4
Railway Officers RPF Society                          4
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Emaar Palm Heights                                    4
Krrish Provence Estate                                4
Orris Aster Court                                     4
Godrej Icon                                           4
Unitech Fresco3.8 ★                                   4
Prime Habitat                                         4
Tata Gurgaon Gateway3.8 ★                             4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Godrej Frontier3.7 ★                                  4
Ramprastha Primera                                    4
Sare Petioles                                         4
Corona Gracieux                                       4
Vatika Xpressions                                     3
Raheja Revanta                                        3
Adani Aangan Arcade                                   3
Sare Green Parc                                       3
Chintels Paradiso3.9 ★                                3
Maxworth City Residences                              3
Deepak Minda                                          3
Unitech The Residences3.7 ★                           3
Sidhartha NCR One                                     3
Raheja Sampada                                        3
Bestech Park View City 23.9 ★                         3
AFNHB Jalvayu Vihar3.7 ★                              3
Pyramid Elite                                         3
Brisk Lumbini Terrace Homes                           3
My Home                                               3
Essel Tower                                           3
Krrish Florence Estate                                3
Piedmont Taksila heights3.6 ★                         3
Tulip White3.5 ★                                      3
Sapphire Eighty Three                                 3
DLF The Grove                                         3
Sukhshanti Apartment                                  3
SS Almeria                                            3
DLF Carlton Estate4.0 ★                               3
DLF Belvedere Towers3.8 ★                             3
AIPL Club Residences                                  3
Unitech Heritage City                                 3
Paras Quartier                                        3
Ambience Lagoon3.9 ★                                  3
Unitech Uniworld Gardens3.8 ★                         3
Raheja Atharva3.6 ★                                   3
Tulip Purple                                          3
Vatika Independent Floors3.8 ★                        3
Shree Arihant Apartment                               3
Mahindra Aura4.2 ★                                    3
Shri Banke Bihari Society3.8 ★                        3
Puri Diplomatic Greens3.9 ★                           3
Sunischit Apartments                                  3
Dhoot Time Residency4.0 ★                             3
ATS Kocoon4.2 ★                                       3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Conscient Habitat3.6 ★                                3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Apex Our Homes                                        3
Guru Gram Haryana CGHS4.1 ★                           3
Siddhartha Apartment                                  3
Kendriya Vihar4.1 ★                                   3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Pivotal Riddhi Siddhi                                 3
Unitech Sunbreeze                                     3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Spaze Privvy The Address3.9 ★                         3
Shri Ram Apartments                                   3
Tulip Petals3.6 ★                                     3
Sidhartha NCR Greens4.3 ★                             3
Valley View Estate                                    3
The Roselia 2                                         3
Satya Element One                                     3
DLF Royalton Tower                                    3
Smriti Apartment                                      3
Jammu and Kashmir Bank Employees CGHS3.7 ★            3
Tulsiani Easy in Homes                                2
BPTP Freedom Park Life4.0 ★                           2
Puri The Aravallis                                    2
Ramprastha City                                       2
Ardee City3.8 ★                                       2
Supertech Hilltown                                    2
Raheja Vanya                                          2
Vatika INXT Floors                                    2
Palam Vihar Society                                   2
M3M Urbana                                            2
Ansal Heights3.2 ★                                    2
Suncity Heights3.7 ★                                  2
Ramprastha The Atrium3.4 ★                            2
Today Callidora                                       2
Park Royal Apartment                                  2
Mapsko Paradise3.9 ★                                  2
MRG World Ultimus                                     2
BPTP Pedestal                                         2
Unitech Uniworld Gardens 23.4 ★                       2
Maruti Vihar                                          2
Vasant Appartments                                    2
Landmark The Residency                                2
Mahindra Luminare4.0 ★                                2
The Close South3.9 ★                                  2
lagoon apartment                                      2
Elan The Presidential                                 2
Pioneer Urban Presidia                                2
M3M Latitude                                          2
Ansal API Celebrity Suites                            2
CGHS Airport Apartment                                2
Bestech Spa Signature                                 2
Green Campus CHS                                      2
DLF The Crest3.6 ★                                    2
DLF The Icon3.7 ★                                     2
Professors Enclave CGHS                               2
BPTP Mansions Park Prime                              2
Paras Irene3.7 ★                                      2
DLF The Belaire3.9 ★                                  2
Suncity Avenue 1023.9 ★                               2
BPTP Amstoria3.8 ★                                    2
Emaar MGF The Enclave                                 2
Vipul Belmonte3.9 ★                                   2
Bestech Park View Sanskruti4.1 ★                      2
M3M Ikonic                                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Viridian The Plaza 106                                2
Tulip Leaf                                            2
Tulip Violet                                          2
Vatika Emilia Floors3.7 ★                             2
Emaar MGF Palm Studios                                2
Orchid Island4.2 ★                                    2
Signature Global The Millennia 3                      2
M3M Sky Lofts                                         2
ROF Aalayas3.8 ★                                      2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
Raheja Atlantis3.8 ★                                  2
Central Park 2 Bellevue                               2
Tulip Orange3.9 ★                                     2
Adani Aangan Galleria                                 2
HCBS Sports Ville                                     2
Housing Board Colony                                  2
Sahara Grace                                          2
Aqua Front Towers                                     2
Oriental Valley CHS                                   2
NBCC Heights3.9 ★                                     2
Supertech Hill Town                                   2
Suncity Avenue 76                                     2
Godrej Nature Plus Serenity                           2
Ashiana Anmol                                         2
Ganga Apartment                                       2
Suposhaa Smartworld Orchard                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
Samaspurkunj                                          2
om appartments                                        2
Lavanya Apartments                                    2
Apartment                                             2
Vipul World Floors                                    2
Milan CGHS 9                                          2
Element One Service                                   2
Breeze Global Heights                                 2
Shapoorji Pallonji Joyville                           2
Dlf City                                              2
Silverglades Hightown Residences                      2
Surendra Avenue 69                                    2
Ambience Caitriona                                    2
Bhagwati Sadan                                        2
Sidhivinayak Apartments                               2
Chanderlok Society                                    2
ss residency                                          2
Uphar lakshya homes                                   2
Godrej Aria , sector 79 , Gurgaon                     2
maa bhagwati residency                                1

In [12]:
df['society'].value_counts().shape

(639,)

In [13]:
import re
df['society']=df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [14]:
df.head(2)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [15]:
df['society'].value_counts().shape

(605,)

In [16]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
40 Lac              29
2.5 Crore           29
60 Lac              29
45 Lac              26
2.1 Crore           26
65 Lac              25
1.85 Crore          23
2.35 Crore          23
35 Lac              23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
2.15 Crore          14
3.4 Crore           14
2.45 Crore          14
3.25 Crore          13
82 Lac              13
78 Lac              13
2.7 Crore           13
38 Lac              13
1.32 Crore          13
92 Lac              13
42 Lac              12
2.8 Crore           12
1.95 Crore          12
1.42 Crore          12
5 Crore             12
Price on Request    11
25 Lac              11
32 Lac              11
88 Lac              11
1.08 Crore          11
28 Lac              10
26 Lac              10
87 Lac              10
1.28 Crore          10
2.55 Crore          10
1.78 Crore          10
1.12 Crore          10
2.85 Crore           9
99 Lac               9
22 Lac               9
36 Lac               9
2.05 Crore           9
4 Crore              9
3.45 Crore           9
1.68 Crore           9
1.72 Crore           9
86 Lac               8
3.2 Crore            8
56 Lac               8
2.75 Crore           8
27 Lac               8
4.25 Crore           8
1.18 Crore           8
1.54 Crore           8
6.5 Crore            8
6 Crore              8
1.76 Crore           8
98 Lac               8
1.26 Crore           8
48 Lac               8
20 Lac               8
1.99 Crore           7
79 Lac               7
46 Lac               7
1.29 Crore           7
2.9 Crore            7
39 Lac               7
72 Lac               7
97 Lac               7
3.7 Crore            7
1.27 Crore           7
1.36 Crore           7
3.3 Crore            7
1.19 Crore           7
1.02 Crore           7
96 Lac               6
1.01 Crore           6
43 Lac               6
3.35 Crore           6
54 Lac               6
4.1 Crore            6
71.5 Lac             6
1.49 Crore           6
3.9 Crore            6
1.98 Crore           6
3.65 Crore           6
5.5 Crore            6
1.07 Crore           6
1.51 Crore           6
2.95 Crore           6
3.05 Crore           6
1.16 Crore           6
21 Lac               6
1.59 Crore           6
1.14 Crore           6
1.39 Crore           6
1.34 Crore           6
1.13 Crore           6
37 Lac               6
1.47 Crore           5
29 Lac               5
1.83 Crore           5
93 Lac               5
4.5 Crore            5
64 Lac               5
24 Lac               5
1.79 Crore           5
2.29 Crore           5
66 Lac               5
1.93 Crore           5
2.12 Crore           5
3.75 Crore           5
6.75 Crore           5
1.33 Crore           5
49 Lac               5
2.78 Crore           5
1.24 Crore           5
1.17 Crore           5
2.22 Crore           5
1.82 Crore           5
1.43 Crore           5
1.91 Crore           5
1.69 Crore           5
1.44 Crore           5
1.92 Crore           5
68 Lac               5
1.62 Crore           5
3.95 Crore           4
6.15 Crore           4
74 Lac               4
28.5 Lac             4
1.71 Crore           4
1.48 Crore           4
5.6 Crore            4
5.9 Crore            4
1.64 Crore           4
3.6 Crore            4
1.77 Crore           4
1.52 Crore           4
62 Lac               4
1.73 Crore           4
5.25 Crore           4
1.37 Crore           4
1.31 Crore           4
1.58 Crore           4
2.09 Crore           4
41.5 Lac             4
1.22 Crore           4
4.3 Crore            4
4.85 Crore           4
7 Crore              4
3.1 Crore            4
1.66 Crore           4
31 Lac               4
89 Lac               4
73 Lac               4
36.5 Lac             4
33 Lac               4
1.23 Crore           4
67 Lac               4
58 Lac               4
4.75 Crore           3
83 Lac               3
34 Lac               3
3.85 Crore           3
2.33 Crore           3
2.79 Crore           3
1.41 Crore           3
91 Lac               3
3.49 Crore           3
1.67 Crore           3
4.8 Crore            3
2.51 Crore           3
2.01 Crore           3
2.08 Crore           3
69 Lac               3
1.09 Crore           3
2.28 Crore           3
3.8 Crore            3
2.03 Crore           3
1.04 Crore           3
2.24 Crore           3
52 Lac               3
3.15 Crore           3
1.21 Crore           3
2.36 Crore           3
1.57 Crore           3
64.5 Lac             3
1.88 Crore           3
84 Lac               3
51 Lac               3
5.8 Crore            3
1.63 Crore           3
72.5 Lac             3
4.2 Crore            3
94 Lac               3
47 Lac               3
41 Lac               2
31.5 Lac             2
2.91 Crore           2
59 Lac               2
3.29 Crore           2
71 Lac               2
87.5 Lac             2
52.56 Lac            2
5.7 Crore            2
1.56 Crore           2
2.26 Crore           2
2.99 Crore           2
2.87 Crore           2
2.57 Crore           2
5.2 Crore            2
4.6 Crore            2
3.21 Crore           2
3.32 Crore           2
1.87 Crore           2
3.55 Crore           2
98.5 Lac             2
56.2 Lac             2
88.5 Lac             2
4.7 Crore            2
4.45 Crore           2
27.75 Lac            2
2.04 Crore           2
4.55 Crore           2
7.5 Crore            2
11 Crore             2
27.1 Lac             2
2.58 Crore           2
2.14 Crore           2
53 Lac               2
77.5 Lac             2
6.2 Crore            2
2.23 Crore           2
53.5 Lac             2
4.49 Crore           2
2.52 Crore           2
2.13 Crore           2
2.17 Crore           2
8.5 Crore            2
8 Crore              2
1.46 Crore           2
25.5 Lac             2
4.26 Crore           2
2.41 Crore           2
2.02 Crore           2
14 Crore             2
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
price                1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
11.25 Crore          1
7.15 Crore           1
2.82 Crore           1
54.99 Lac            1
4.95 Crore           1
5.31 Crore           1
3.19 Crore           1
4.4 Crore            1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
2.72 Crore           1
2.21 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
55.5 Lac             1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
9.14 Crore           1
8.35 Crore           1
81 Lac               1
26.1 Lac             1
1.06 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
47.5 Lac             1
2.77 Crore           1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
5.15 Crore           1
9.3 Crore            1
1.74 Crore           1
4.21 Crore           1
4.16 Crore           1
4.52 Crore           1
1.84 Crore           1
8.44 Crore           1
13.2 Crore           1
2.92 Crore           1
2.38 Crore           1
97.5 Lac             1
2.64 Crore           1
2.49 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
9.95 Crore           1
9.2 Crore            1
49.5 Lac             1
16 Lac               1
2.86 Crore           1
86.92 Lac            1
94.99 Lac            1
88.4 Lac             1
3.72 Crore           1
57 Lac               1
95.5 Lac             1
96.07 Lac            1
19 Lac               1
70.85 Lac            1
7.52 Crore           1
40.3 Lac             1
32.5 Lac             1
2.96 Crore           1
1.53 Crore           1
82.5 Lac             1
61 Lac               1
15 Crore             1
7.8 Crore            1
1.97 Crore           1
39.5 Lac             1
4.02 Crore           1
3.98 Crore           1
54.8 Lac             1
2.69 Crore           1
2.54 Crore           1
37.5 Lac             1
97.04 Lac            1
3.23 Crore           1
7.9 Crore            1
6.02 Crore           1
29.8 Lac             1
94.5 Lac             1
2.44 Crore           1
9 Crore              1
3.99 Crore           1
64.45 Lac            1
37.1 Lac             1
7.4 Crore            1
3.78 Crore           1
98.88 Lac            1
68.85 Lac            1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

In [17]:
df[df['price']=='Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1645,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1973,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2055,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2358,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2523,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2550,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2641,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2960,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2973,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2974,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [18]:
df.shape

(3028, 18)

In [19]:
df=df[df['price'] != 'Price on Request']

In [20]:
df.shape

(3017, 18)

In [21]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [22]:
def convert_to_crore(value):
    value = str(value).strip().lower()

    if 'crore' in value:
        return float(value.replace('crore', '').strip())

    elif 'lac' in value or 'lakh' in value:
        num = (
            value.replace('lac', '')
                 .replace('lakh', '')
                 .strip()
        )
        return float(num) / 100

    return None  # or float(value) if needed

In [23]:
# Apply on column
df['price'] = df['price'].apply(convert_to_crore)

In [24]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
528,1 BHK Flat in Palam Vihar,bestech park view residency,0.562,"₹ 8,632/sq.ft.",Carpet area: 651 (60.48 sq.m.),1 Bedroom,1 Bathroom,2 Balconies,NaN,"Palam Vihar, Gurgaon, Haryana",6th of 8 Floors,South,5 to 10 Year Old,"['Dwarka Sector 21 Metro Station', 'HUDA Marke...","Situated in palam vihar, gurgaon, bestech park...","['1 Wardrobe', '2 Fan', '1 Geyser', '2 Light',...","['Security / Fire Alarm', 'Power Back-up', 'Li...","['Green Area5 out of 5', 'Construction4 out of..."
1510,3 BHK Flat in Sector 56 Gurgaon,professors enclave cghs,1.540,"₹ 8,324/sq.ft.",Super Built up area 2000(185.81 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,2 Balconies,"Pooja Room,Servant Room","Sector 56, Sector 56 Gurgaon, Gurgaon, Haryana",6th of 9 Floors,South,10+ Year Old,"['Sector metro station', 'Sector metro station...",This 3 bhk apartment is available for sale in ...,"['5 Fan', '1 Exhaust Fan', '3 Geyser', '12 Lig...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'H...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
2222,2 BHK Flat in Sector 91 Gurgaon,tarc maceo,0.950,"₹ 5,954/sq.ft.",Super Built up area 1310(121.7 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 91 Gurgaon, Gurgaon, Haryana",10th of 13 Floors,East,1 to 5 Year Old,"['Manish Gallexie 91', 'Dwarka Expressway', 'R...",I want to sell my 2bhk apartment in anant raj ...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4 out of..."
2050,3 BHK Flat in Sector 89 A Gurgaon,ats marigold,1.850,"₹ 8,604/sq.ft.",Super Built up area 2150(199.74 sq.m.),3 Bedrooms,3 Bathrooms,3+ Balconies,Servant Room,"Sector 89 A Gurgaon, Gurgaon, Haryana",12nd of 22 Floors,South-West,0 to 1 Year Old,"['Reliance Trends Newtown Square Mall', 'Dwark...",The possession of the house would be in next 4...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...",NaN
815,3 BHK Flat in Sector 111 Gurgaon,puri diplomatic greens,2.580,"₹ 11,727/sq.ft.",Super Built up area 2200(204.39 sq.m.),3 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,"N/a, Sector 111 Gurgaon, Gurgaon, Haryana",9th of 21 Floors,East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Situated in sector 111 gurgaon, puri diplomati...",[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."

In [25]:
df['price_per_sqft']=df['price_per_sqft'].str.split().str[1].str.split('/').str[0].str.replace(",","").astype(float)

In [26]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [27]:
df['bedRoom'].isnull().sum()

np.int64(19)

In [28]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2850,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in New Palam Vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2853,2 BHK Flat in Sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2925,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2928,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2994,4 BHK Flat in DLF Phase 4,chanderlok society,NaN,7234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2995,3 BHK Flat in Sector 9A Gurgaon,jammu and kashmir bank employees cghs,NaN,6129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,3 BHK Flat in Sector 37C Gurgaon,ild greens,NaN,4723.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,3 BHK Flat in Adarsh Nagar,ss residency,NaN,4818.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,3 BHK Flat in Rajendra Park,uphar lakshya homes,NaN,4200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,2 BHK Flat in Sector 79 Gurgaon,supertech araville,NaN,9000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3000,3 BHK Flat in Sector 37C Gurgaon,corona optus,NaN,6361.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3001,3 BHK Flat in Sector 78 Gurgaon,umang monsoon breeze,NaN,6493.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3002,3 BHK Flat in Sector 88A Gurgaon,godrej oasis,NaN,8108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3003,"2 BHK Flat in Godrej Aria , sector 79 , Gurgaon","godrej aria , sector 79 , gurgaon",NaN,11111.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df=df[~df['bedRoom'].isnull()]

In [30]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
945,1 BHK Flat in Sector 2 Gurgaon,ansal api celebrity suites,0.60,8163.0,Super Built up area 735(68.28 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,NaN,"Sector 2 Gurgaon, Gurgaon, Haryana",5th of 15 Floors,North-East,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Looking for a 1 bhk property for sale in gurga...,"['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Intercom Facility', 'Lift(s...",NaN
2030,3 BHK Flat in Sector 81 Gurgaon,bestech park view ananda,1.35,7541.0,Carpet area: 1790 (166.3 sq.m.),3 Bedrooms,3 Bathrooms,3+ Balconies,NaN,"Sector 81 Gurgaon, Gurgaon, Haryana",8th of 15 Floors,North,10+ Year Old,"['Metro Station Kankrola sec 87', 'Sapphire 83...",Perfect sunlight in all the 3 rooms and drawin...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction5 out of..."
1099,2 BHK Flat in Sector 107 Gurgaon,m3m woodshire,0.88,6442.0,Super Built up area 1366(126.91 sq.m.),2 Bedrooms,2 Bathrooms,3+ Balconies,NaN,"Sector 107 Gurgaon, Gurgaon, Haryana",3rd of 14 Floors,East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Corner and airy flat with ample sunlight throu...,"['1 Bed', '5 Fan', '1 Sofa', '10 Light', '3 AC...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction5 out ..."
963,3 BHK Flat in Sector 108 Gurgaon,sobha city,2.45,14040.0,Super Built up area 1745(162.12 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sector 108 Gurgaon, Gurgaon, Haryana",15th of 19 Floors,West,1 to 5 Year Old,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...",Check out this 3 bhk apartment for sale in sob...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4.5 out of..."
2343,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,0.45,6475.0,Built Up area: 695 (64.57 sq.m.)Carpet area: 5...,2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",19th of 19 Floors,North,undefined,NaN,Signature roselia 2 bhk. It is a good location...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."

In [31]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
bedRoom          1
Name: count, dtype: int64

In [32]:
df[df['bedRoom']=='bedRoom']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
286,property_name,society,NaN,NaN,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating

In [33]:
df.drop(df.index[df['bedRoom'] == 'bedRoom'], inplace=True)

In [34]:
df['bedRoom']=df['bedRoom'].str.split(' ').str[0].astype(int)

In [35]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [36]:
df['bathroom'].isnull().sum()

np.int64(0)

In [37]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [38]:
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [39]:
df['balcony'].isnull().sum()

np.int64(0)

In [40]:
def balcony_to_int(value):
    if pd.isnull(value):
        return 0
    else:
        if value=='No Balcony':
            return 0
        return int(value.split()[0])

In [41]:
df['balcony']=df['balcony'].str.split().str[0].str.replace('No','0')

In [42]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Pooja Room,Study Room,Others                       2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Store Room,Pooja Room,Servant Room                 1
Study Room,Servant Room,Pooja Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Servant Room,Pooja Room,Store Room                 1
Store Room,Study Room                              1
Study Room,Store Room                              1
Servant Room,Pooja Room,Store Room,Study Room      1
Servant Room,Study Room,Pooja Room                 1
Servant Room,Pooja Room,Study Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [43]:
df['additionalRoom'].isnull().sum()

np.int64(1305)

In [44]:
df['additionalRoom']=df['additionalRoom'].fillna('not available',inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26668\941797568.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['additionalRoom']=df['additionalRoom'].fillna('not available',inplace=True)

In [45]:
df['additionalRoom']=df['additionalRoom'].str.lower()

In [46]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [47]:
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
3rd   of 3 Floors           26
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 14 Floors          24
8th   of 19 Floors          24
5th   of 14 Floors          24
11st   of 14 Floors         23
1st   of 1 Floors           23
9th   of 9 Floors           23
9th   of 14 Floors          23
2nd   of 3 Floors           22
5th   of 12 Floors          22
2nd   of 14 Floors          21
8th   of 18 Floors          20
6th   of 18 Floors          18
10th   of 19 Floors         18
Ground of 1 Floors          17
12nd   of 12 Floors         17
10th   of 18 Floors         17
7th   of 18 Floors          17
9th   of 13 Floors          17
7th   of 15 Floors          17
5th   of 15 Floors          16
3rd   of 18 Floors          16
1st   of 3 Floors           15
9th   of 15 Floors          15
2nd   of 12 Floors          15
6th   of 12 Floors          15
6th   of 19 Floors          14
6th   of 10 Floors          13
Ground of 4 Floors          13
7th   of 7 Floors           13
1st   of 2 Floors           13
5th   of 5 Floors           13
10th   of 26 Floors         13
3rd   of 13 Floors          13
10th   of 10 Floors         12
6th   of 15 Floors          12
4th   of 13 Floors          11
8th   of 12 Floors          11
8th   of 8 Floors           11
4th   of 10 Floors          11
6th   of 6 Floors           11
17th   of 17 Floors         11
9th   of 26 Floors          11
15th   of 19 Floors         11
11st   of 18 Floors         11
9th   of 24 Floors          11
16th   of 19 Floors         11
4th   of 15 Floors          10
4th   of 12 Floors          10
3rd   of 5 Floors           10
2nd   of 19 Floors          10
7th   of 26 Floors          10
3rd   of 9 Floors           10
10th   of 12 Floors         10
1st   of 26 Floors          10
12nd   of 18 Floors         10
7th   of 21 Floors          10
7th   of 13 Floors          10
6th   of 13 Floors          10
12nd   of 17 Floors          9
5th   of 18 Floors           9
9th   of 20 Floors           9
8th   of 22 Floors           9
18th   of 19 Floors          9
13rd   of 14 Floors          9
8th   of 15 Floors           9
3rd   of 12 Floors           9
14th   of 15 Floors          9
6th   of 16 Floors           9
6th   of 26 Floors           9
7th   of 12 Floors           9
7th   of 17 Floors           9
15th   of 29 Floors          9
14th   of 19 Floors          9
1st   of 19 Floors           8
9th   of 12 Floors           8
8th   of 13 Floors           8
2nd   of 5 Floors            8
14th   of 24 Floors          8
3rd   of 19 Floors           8
3rd   of 15 Floors           8
10th   of 17 Floors          8
2nd   of 15 Floors           8
8th   of 26 Floors           8
5th   of 9 Floors            8
2nd   of 8 Floors            8
4th   of 26 Floors           8
12nd   of 19 Floors          8
12nd   of 26 Floors          8
10th   of 13 Floors          8
12nd   of 24 Floors          8
8th   of 24 Floors           8
9th   of 18 Floors           8
5th   of 13 Floors           8
13rd   of 13 Floors          7
12nd   of 13 Floors          7
7th   of 19 Floors           7
5th   of 20 Floors           7
11st   of 11 Floors          7
11st   of 13 Floors          7
1st   of 13 Floors           7
2nd   of 17 Floors           7
16th   of 16 Floors          7
8th   of 10 Floors           7
11st   of 26 Floors          7
2nd   of 10 Floors           7
9th   of 19 Floors           7
8th   of 21 Floors           7
5th   of 29 Floors           7
10th   of 21 Floors          7
12nd   of 15 Floors          7
11st   of 24 Floors          7
2nd   of 13 Floors           7
4th   of 19 Floors           7
5th   of 25 Floors           6
14th   of 27 Floors          6
11st   of 12 Floors          6
16th   of 18 Floors          6
7th   of 20 Floors           6
10th   of 20 Floors          6
Ground of 3 Floors           6
19th   of 19 Floors          6
15th   of 15 Floors          6
4th   of 18 Floors           6
1st   of 10 Floors           6
12nd   of 22 Floors          6
17th   of 19 Floors          6
Ground of 16 Floors          6
10th   of 15 Floors          6
2nd   of 20 Floors           6
5th   of 22 Floors           6
10th   of 29 Floors          6
5th   of 10 Floors           6
6th   of 9 Floors            6
3rd   of 25 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
1st   of 5 Floors            6
11st   of 19 Floors          6
5th   of 8 Floors            5
3rd   of 20 Floors           5
10th   of 25 Floors          5
9th   of 30 Floors           5
6th   of 20 Floors           5
11st   of 25 Floors          5
1st   of 15 Floors           5
1st   of 12 Floors           5
11st   of 30 Floors          5
1st   of 7 Floors            5
5th   of 19 Floors           5
9th   of 22 Floors           5
6th   of 17 Floors           5
4th   of 22 Floors           5
14th   of 29 Floors          5
7th   of 27 Floors           5
15th   of 28 Floors          5
12nd   of 29 Floors          5
11st   of 16 Floors          5
11st   of 29 Floors          5
Ground of 21 Floors          5
10th   of 24 Floors          5
Ground of 12 Floors          5
15th   of 21 Floors          5
10th   of 27 Floors          5
15th   of 18 Floors          5
7th   of 8 Floors            5
8th   of 9 Floors            5
18th   of 29 Floors          5
8th   of 30 Floors           5
16th   of 26 Floors          5
12nd   of 21 Floors          5
6th   of 11 Floors           5
4th   of 9 Floors            5
Ground of 19 Floors          5
4th   of 27 Floors           5
14th   of 16 Floors          5
9th   of 11 Floors           5
25th   of 25 Floors          4
20th   of 20 Floors          4
18th   of 32 Floors          4
1st   of 18 Floors           4
14th   of 17 Floors          4
3rd   of 11 Floors           4
23rd   of 26 Floors          4
4th   of 8 Floors            4
12nd   of 16 Floors          4
11st   of 15 Floors          4
2nd   of 16 Floors           4
9th   of 10 Floors           4
7th   of 9 Floors            4
22nd   of 24 Floors          4
19th   of 40 Floors          4
15th   of 32 Floors          4
14th   of 18 Floors          4
14th   of 21 Floors          4
7th   of 10 Floors           4
19th   of 24 Floors          4
11st   of 20 Floors          4
11st   of 17 Floors          4
17th   of 25 Floors          4
8th   of 16 Floors           4
20th   of 26 Floors          4
12nd   of 30 Floors          4
17th   of 24 Floors          4
5th   of 16 Floors           4
22nd   of 30 Floors          4
2nd   of 9 Floors            4
15th   of 25 Floors          4
14th   of 26 Floors          4
17th   of 18 Floors          4
6th   of 30 Floors           4
Ground of 13 Floors          4
5th   of 24 Floors           4
15th   of 26 Floors          4
2nd   of 11 Floors           4
8th   of 20 Floors           4
15th   of 16 Floors          4
17th   of 26 Floors          4
13rd   of 25 Floors          4
7th   of 24 Floors           4
5th   of 23 Floors           4
Ground of 17 Floors          4
15th   of 23 Floors          4
7th   of 11 Floors           4
13rd   of 19 Floors          4
13rd   of 21 Floors          4
3rd   of 22 Floors           4
3rd   of 17 Floors           4
3rd   of 10 Floors           4
5th   of 17 Floors           3
21st   of 24 Floors          3
6th   of 24 Floors           3
1st   of 25 Floors           3
3rd   of 26 Floors           3
1st   of 11 Floors           3
15th   of 20 Floors          3
10th   of 16 Floors          3
1st   of 35 Floors           3
30th   of 32 Floors          3
8th   of 25 Floors           3
31st   of 32 Floors          3
18th   of 18 Floors          3
9th   of 16 Floors           3
26th   of 30 Floors          3
16th   of 20 Floors          3
3rd   of 8 Floors            3
7th   of 23 Floors           3
10th   of 30 Floors          3
5th   of 30 Floors           3
15th   of 40 Floors          3
8th   of 11 Floors           3
18th   of 30 Floors          3
5th   of 26 Floors           3
Ground of 18 Floors          3
9th   of 21 Floors           3
19th   of 29 Floors          3
6th   of 8 Floors            3
15th   of 39 Floors          3
8th   of 40 Floors           3
2nd   of 26 Floors           3
12nd   of 23 Floors          3
10th   of 28 Floors          3
3rd   of 16 Floors           3
4th   of 20 Floors           3
17th   of 30 Floors          3
17th   of 29 Floors          3
19th   of 30 Floors          3
6th   of 29 Floors           3
17th   of 20 Floors          3
11st   of 27 Floors          3
27th   of 27 Floors          3
4th   of 21 Floors           3
14th   of 32 Floors          3
10th   of 23 Floors          3
2nd   of 22 Floors           3
24th   of 24 Floors          3
21st   of 22 Floors          3
4th   of 16 Floors           3
4th   of 29 Floors           3
19th   of 21 Floors          3
6th   of 21 Floors           3
8th   of 17 Floors           3
20th   of 28 Floors          3
Ground of 26 Floors          3
12nd   of 27 Floors          3
6th   of 22 Floors           3
6th   of 23 Floors           3
9th   of 40 Floors           3
18th   of 26 Floors          3
15th   of 22 Floors          3
13rd   of 15 Floors          3
23rd   of 23 Floors          3
9th   of 29 Floors           2
43   of 47 Floors            2
2nd   of 25 Floors           2
20th   of 22 Floors          2
11st   of 21 Floors          2
4th   of 34 Floors           2
Lower Ground of 4 Floors     2
10th   of 22 Floors          2
8th   of 34 Floors           2
1st   of 22 Floors           2
8th   of 32 Floors           2
39th   of 40 Floors          2
14th   of 20 Floors          2
20th   of 23 Floors          2
9th   of 17 Floors           2
2nd   of 24 Floors           2
16th   of 24 Floors          2
19th   of 20 Floors          2
Ground of 23 Floors          2
4th   of 11 Floors           2
18th   of 21 Floors          2
14th   of 28 Floors          2
16th   of 27 Floors          2
16th   of 32 Floors          2
8th   of 29 Floors           2
3rd   of 32 Floors           2
7th   of 29 Floors           2
16th   of 21 Floors          2
25th   of 30 Floors          2
9th   of 28 Floors           2
13rd   of 40 Floors          2
6th   of 31 Floors           2
1st   of 24 Floors           2
12nd   of 25 Floors          2
4th   of 5 Floors            2
7th   of 16 Floors           2
28th   of 30 Floors          2
Ground of 51 Floors          2
10th   of 32 Floors          2
7th   of 36 Floors           2
3rd   of 29 Floors           2
3rd   of 27 Floors           2
10th   of 11 Floors          2
2nd   of 21 Floors           2
8th   of 28 Floors           2
15th   of 17 Floors          2
20th   of 25 Floors          2
7th   of 22 Floors           2
2nd   of 40 Floors           2
9th   of 27 Floors           2
21st   of 27 Floors          2
2nd   of 32 Floors           2
18th   of 24 Floors          2
23rd   of 34 Floors          2
1st   of 8 Floors            2
1st   of 20 Floors           2
1st   of 30 Floors           2
22nd   of 25 Floors          2
2nd   of 7 Floors            2
2nd   of 18 Floors           2
3rd   of 24 Floors           2
16th   of 34 Floors          2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
16th   of 30 Floors          2
23rd   of 29 Floors          2
25th   of 29 Floors          2
11st   of 23 Floors          2
8th   of 23 Floors           2
19th   of 27 Floors          2
10th   of 40 Floors          2
13rd   of 30 Floors          2
7th   of 30 Floors           2
13rd   of 20 Floors          2
27th   of 29 Floors          2
15th   of 31 Floors          2
2nd   of 28 Floors           2
2nd   of 6 Floors            2
24th   of 30 Floors          2
16th   of 36 Floors          2
5th   of 11 Floors           2
1st   of 16 Floors           2
1st   of 17 Floors           2
3rd   of 33 Floors           2
17th   of 33 Floors          2
15th   of 45 Floors          2
40th   of 40 Floors          2
31st   of 40 Floors          1
11st   of 22 Floors          1
Ground of 11 Floors          1
29th   of 31 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
32nd   of 55 Floors          1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
20th   of 34 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
33rd   of 48 Floors          1
35th   of 35 Floors          1
26th   of 47 Floors          1
Ground of 24 Floors          1
7th   of 25 Floors           1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
1st   of 44 Floors           1
24th   of 31 Floors          1
24th   of 51 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
25th   of 36 Floors          1
21st   of 28 Floors          1
7th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
3rd   of 6 Floors            1
20th   of 40 Floors          1
9th   of 42 Floors           1
8th   of 31 Floors           1
20th   of 30 Floors          1
18th   of 51 Floors          1
24th   of 27 Floors          1
19th   of 22 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
12nd   of 39 Floors          1
38th   of 40 Floors          1
18th   of 40 Floors          1
35th   of 51 Floors          1
22nd   of 28 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
15th   of 27 Floors          1
3rd   of 40 Floors           1
6th   of 25 Floors           1
16th   of 25 Floors          1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
10th   of 39 Floors          1
21st   of 26 Floors          1
22nd   of 40 Floors          1
16th   of 41 Floors          1
7th   of 40 Floors           1
12nd   of 40 Floors          1
3rd   of 28 Floors           1
17th   of 28 Floors          1
3rd   of 30 Floors           1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
12nd   of 34 Floors          1
5th   of 34 Floors           1
9th   of 25 Floors           1
45   of 47 Floors            1
Ground of 25 Floors          1
9th   of 23 Floors           1
33rd   of 33 Floors          1
1st   of 6 Floors            1
20th   of 24 Floors          1
13rd   of 17 Floors          1
Ground of 6 Floors           1
Basement of 13 Floors        1
18th   of 22 Floors          1
17th   of 22 Floors          1
24th   of 36 Floors          1
3rd   of 36 Floors           1
5th   of 6 Floors            1
8th   of 35 Floors           1
Lower Ground of 1 Floors     1
5th   of 35 Floors           1
Ground of 2 Floors           1
10th   of 33 Floors          1
18th   of 35 Floors          1
17th   of 31 Floors          1
21st   of 23 Floors          1
Ground of 5 Floors           1
Ground of 40 Floors          1
13rd   of 22 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
23rd   of 24 Floors          1
17th   of 47 Floors          1
4th   of 6 Floors            1
30th   of 34 Floors          1
13rd   of 47 Floors          1
34th   of 42 Floors          1
29th   of 39 Floors          1
18th   of 20 Floors          1
3rd   of 31 Floors           1
27th   of 30 Floors          1
34th   of 34 Floors          1
5th   of 36 Floors           1
19th   of 32 Floors          1
16th   of 45 Floors          1
22nd   of 23 Floors          1
7th   of 28 Floors           1
21st   of 36 Floors          1
14th   of 41 Floors          1
Ground of 29 Floors          1
22nd   of 26 Floors          1
13rd   of 26 Floors          1
14th   of 25 Floors          1
3rd   of 7 Floors            1
Ground of 22 Floors          1
13rd   of 34 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [48]:
df['floorNum']=df['floorNum'].str.split().str[0].str.replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [49]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [50]:
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [62]:
df['facing'].isnull().sum()

np.int64(874)

In [ ]:
df['facing'].fillna('NA',inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26668\3133442517.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['facing'].fillna('N',inplace=True)

0             West
1             West
2                N
3                N
4                N
5                N
6                N
7                N
8       North-East
9                N
10               N
11               N
12               N
13      South-East
14               N
15               N
16               N
17               N
18            East
19      North-East
20               N
21           North
22               N
23      South-West
24            East
26               N
27      North-East
28      South-East
29           North
30      North-East
31               N
32               N
33               N
34               N
35      North-East
36               N
37            East
38      North-East
39           North
40           North
41      North-West
42               N
43           North
44            East
45               N
46            East
47            West
48               N
49            East
50               N
51           North
52      North-East
53               N
54               N
55               N
56           South
57               N
58           South
59      South-East
60               N
61               N
62               N
63           North
64            East
65               N
66           North
67               N
68               N
69               N
70      North-East
71      North-East
72               N
73               N
74            East
75      North-East
76               N
77           South
78               N
79      North-East
80           North
81               N
82               N
83               N
84               N
85            East
86            East
87               N
88               N
89               N
90           South
91               N
92           South
93               N
94               N
95               N
96               N
97               N
98            East
99           North
100              N
101          South
102              N
103              N
104          North
105              N
106              N
107              N
108              N
109              N
110              N
111              N
112              N
113              N
114     South-West
115              N
116           East
117              N
118           East
119     North-East
120              N
121     North-East
122              N
123           East
124     North-East
125              N
126              N
127              N
128              N
129              N
130              N
131              N
132              N
133              N
134              N
135              N
136              N
137           East
138              N
139              N
140     South-West
141              N
142              N
143           East
144              N
145           East
146              N
147           East
148              N
149           West
150              N
151              N
152              N
153              N
154           West
155              N
156              N
157              N
158              N
159              N
160     North-East
161              N
162              N
163          South
164           East
165              N
166           East
167              N
168              N
169              N
170              N
171           West
172              N
173              N
174     North-East
175           West
176           East
177     North-East
178           East
179     North-East
180              N
181              N
182              N
183          South
184     North-West
185     North-East
186              N
187              N
188           East
189              N
190              N
191              N
192              N
193          North
194              N
195           West
196              N
197           East
198              N
199           East
200           East
201     North-East
202              N
203              N
204           East
205           East
206           West
207              N
208     North-East
209              N
210              N
211              N
212           East
213           East
214     South-East
215           East
216           East
217     South-East
218              N
219              N
220           East
221     North-East
222           East
223              N
224              N
225          North
226              N
227              N
228     South-East
229              N
230              N
231           East
232              N
233              N
234          North
235     North-East
236           East
237          South
238              N
239              N
240           East
241           East
242           East
243              N
244          North
245              N
246           West
247              N
248              N
249              N
250              N
251           East
252           East
253              N
254              N
255              N
256           East
257              N
258              N
259              N
260     North-East
261              N
262     North-East
263          South
264              N
265     North-East
266              N
267              N
268              N
269          North
270              N
271              N
272              N
273     North-East
274              N
275              N
276              N
277     North-East
278              N
279              N
280              N
281           West
282           East
283              N
284              N
285     North-East
287     South-East
288          South
289           West
290          North
291     South-West
292     South-East
293     South-East
294     South-East
295     South-East
296              N
297              N
298     South-West
299              N
300              N
301     South-West
302           East
303           West
304          North
305     North-West
306           East
307              N
308          South
309          North
310          North
311     North-West
312              N
313     South-West
314           East
315          North
316     North-West
317              N
318              N
319     North-West
320          South
321           West
322          North
323     South-West
324     South-East
325              N
326     South-West
327              N
328     South-West
329           East
330           West
331          North
332     North-West
333           East
334              N
335          North
336     North-West
337     South-West
338          North
339     North-West
340              N
341              N
342           East
343     North-West
344              N
345     South-East
346              N
347          South
348     North-East
349     South-East
350              N
351     North-West
352     North-East
353     South-West
354     South-West
355     North-East
356           West
357           East
358           East
359           East
360           East
361           East
362     North-West
363           East
364     North-East
365           West
366     North-East
367     North-East
368              N
369     North-West
370     North-East
371     South-East
372           East
373          South
374           West
375          North
376     North-West
377     North-East
378              N
379              N
380              N
381     North-East
382           East
383           West
384              N
385          North
386           East
387           East
388          North
389     South-East
390              N
391     North-East
392     North-East
393     North-East
394           East
395     South-West
396     North-East
397     North-East
398           East
399          North
400     North-East
401          North
402           East
403          North
404     North-West
405     North-East
406              N
407              N
408     South-West
409     North-East
410           West
411          South
412     South-East
413           East
414     South-West
415     South-West
416           West
417          North
418     South-West
419     North-East
420           West
421          South
422          South
423          North
424              N
425              N
426     North-East
427     North-East
428          North
429          South
430     North-West
431              N
432     South-West
433     North-East
434          North
435     South-West
436           East
437     South-West
438          North
439     North-West
440     North-East
441              N
442          North
443          South
444          South
445           East
446           East
447          South
448           East
449           East
450     South-East
451          South
452     North-East
453     North-East
454     North-East
455          North
456     North-East
457          North
458           West
459     South-East
460     South-East
461     North-East
462     North-East
463     South-East
464     North-East
465     North-East
466     North-East
467     North-East
468     South-West
469     North-East
470     North-East
471           East
472     South-East
473          South
474     North-East
475           West
476              N
477          North
478           East
479     North-East
480     North-East
481          South
482     North-West
483     North-West
484     North-West
485     North-East
486          South
487     South-East
488     South-West
489              N
490     North-East
491     North-East
492     North-East
493           West
494     South-West
495              N
496     North-East
497     North-West
498           East
499           West
500          North
501          South
502          South
503           East
504     South-East
505           East
506     South-West
507     South-East
508          North
509     South-East
510          North
511     South-East
512           East
513     North-East
514     North-West
515          North
516     North-East
517          South
518           East
519          North
520           East
521          South
522          South
523          South
524          South
525           East
526     South-West
527           East
528          South
529          South
530     North-West
531           East
532     North-East
533     South-West
534           East
535           East
536     North-West
537           East
538     North-East
539          South
540     North-East
541     North-East
542           East
543     South-East
544           West
545          North
546     North-East
547          North
548          North
549          North
550          North
551           East
552          North
553     North-West
554     North-West
555     North-West
556     North-West
557           West
558          North
559     North-East
560     North-East
561     North-East
562          South
563          South
564           West
565     South-West
566           East
567           East
568          South
569     North-East
570           West
571     South-West
572     North-West
573     North-East
574     North-East
575     North-East
576     South-West
577     North-East
578           West
579     North-East
580     North-East
581     North-East
582     North-East
583          North
584     North-East
585           West
586     North-East
587     South-West
588     North-East
589     South-West
590           West
591     North-East
592           East
593           East
594          North
595          South
596     South-East
597           East
598     South-West
599           East
600          South
601          South
602     North-East
603           East
604           West
605          North
606     South-West
607     North-East
608          North
609     North-East
610          North
611     North-East
612     North-East
613     North-East
614     North-East
615     North-East
616     North-East
617           West
618     North-East
619     South-West
620     South-West
621          North
622     North-East
623           East
624          South
625           East
626          South
627     North-East
628              N
629           East
630           East
631           East
632          North
633     North-West
634          South
635          South
636           West
637     North-West
638     South-East
639          South
640     South-West
641          South
642           East
643     North-East
644     North-East
645     North-East
646           East
647           East
648          South
649          South
650     South-West
651           East
652           West
653           West
654     North-East
655          North
656     South-East
657     North-East
658          South
659          South
660           East
661           East
662              N
663           East
664     North-East
665     South-East
666     North-East
667     South-East
668     North-East
669     South-West
670           East
671              N
672     South-East
673          North
674     North-East
675     North-East
676     North-East
677     South-West
678          North
679     South-West
680           East
681          South
682           East
683           East
684          South
685           West
686           East
687     North-East
688          North
689           East
690          North
691     North-East
692     North-East
693           West
694     North-East
695     North-East
696           East
697     North-East
698           West
699           West
700     North-West
701              N
702              N
703     North-East
704           East
705          North
706           East
707          North
708     North-East
709          North
710           East
711     South-East
712          South
713     North-East
714     North-East
715          North
716           East
717          North
718          North
719          North
720     North-East
721     South-East
722           East
723           West
724           East
725     North-East
726     North-East
727     North-East
728          North
729     North-East
730          North
731           East
732     North-East
733     North-East
734     North-East
735           West
736           West
737           East
738     South-East
739     South-East
740     North-East
741     South-East
742          South
743     North-East
744           East
745     North-East
746           West
747           West
748           East
749     North-East
750     North-East
751     North-East
752           East
753              N
754     North-West
755           West
756          South
757          South
758          North
759     South-West
760     South-West
761           East
762     North-East
763     South-West
764     North-East
765          South
766     North-East
767     South-West
768     South-East
769     North-East
770     North-East
771     North-East
772           East
773     South-West
774     North-East
775          North
776           West
777     South-East
778          South
779          North
780     North-West
781     South-West
782           East
783          North
784     North-East
785          North
786     South-East
787     North-East
788     North-East
789           East
790          South
791          South
792     South-East
793     South-West
794     North-East
795           West
796           East
797          North
798     North-East
799           West
800     North-East
801           East
802           East
803           East
804     North-West
805           West
806           East
807          North
808           West
809          North
810          North
811          North
812     North-East
813          North
814     North-East
815           East
816           East
817           East
818     North-East
819     North-East
820     North-East
821     North-East
822           East
823     North-East
824     North-West
825     North-East
826     South-West
827     South-East
828           West
829     North-West
830           East
831           East
832           West
833           East
834           West
835     North-East
836     North-East
837          South
838           East
839     North-East
840     South-West
841     South-West
842     North-West
843          South
844     North-West
845           West
846          South
847              N
848          South
849          South
850     North-East
851     North-West
852          North
853     North-East
854     North-East
855           East
856           East
857     South-East
858          North
859          North
860          North
861     South-East
862     South-West
863          South
864     North-East
865     North-East
866           East
867     South-East
868           East
869     South-West
870     South-West
871     North-West
872     North-West
873     North-West
874     North-West
875          North
876           East
877           East
878           West
879           East
880          North
881           East
882     North-East
883           East
884           East
885          North
886     South-East
887           West
888     North-East
889     North-East
890           East
891           East
892           West
893          North
894          North
895           East
896     North-East
897          South
898           East
899          North
900     North-East
901     South-East
902     South-East
903     North-East
904           East
905     North-East
906          North
907          North
908     North-West
909           West
910          North
911           West
912     North-East
913           East
914           East
915           East
916     North-East
917          North
918           West
919           East
920     North-West
921     North-West
922          North
923          North
924     North-East
925     North-East
926     North-East
927     North-East
928     North-East
929          North
930     North-East
931     North-East
932          North
933           West
934           West
935     North-East
936     North-East
937           East
938          North
939           East
940     South-East
941           East
942     North-West
943          North
944     North-East
945     North-East
946     North-East
947          South
948     North-West
949     North-East
950     North-East
951           West
952           West
953     South-East
954          North
955     North-West
956     North-East
957          South
958          North
959           East
960     North-East
961          North
962     North-East
963           West
964     North-West
965     North-East
966     North-East
967           East
968     North-East
969     South-East
970          South
971     North-West
972     South-East
973     South-West
974     North-West
975     South-East
976     North-East
977          North
978     North-East
979     South-West
980     South-West
981     South-West
982     South-West
983     South-West
984          North
985     South-East
986           East
987     North-East
988          North
989     North-East
990          North
991     North-West
992          South
993     South-East
994          South
995           West
996           East
997     South-West
998           West
999           West
1000         South
1001         South
1002         North
1003         North
1004    North-West
1005    North-West
1006             N
1007    North-West
1008    South-East
1009         South
1010          East
1011    North-East
1012    North-East
1013         South
1014         North
1015    North-East
1016    North-East
1017          East
1018          West
1019    North-East
1020    North-East
1021    North-East
1022          East
1023    North-East
1024    North-East
1025    North-East
1026    North-West
1027    North-East
1028          East
1029    North-East
1030    North-East
1031    South-West
1032    South-West
1033    South-East
1034    North-West
1035    North-West
1036    North-West
1037          West
1038          East
1039          West
1040    North-East
1041         North
1042          East
1043    North-West
1044    North-West
1045         North
1046    North-East
1047    North-West
1048         South
1049    South-East
1050    South-West
1051          West
1052    North-East
1053    North-East

In [65]:
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [60]:
df['facing'].isnull().sum()

np.int64(874)

In [61]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [66]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [67]:
df.insert(loc=1,column='property_type',value='flat')

In [68]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [70]:
df.info()

<class 'pandas.DataFrame'>
Index: 2997 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   str
 1   property_type    2997 non-null   str
 2   society          2997 non-null   str
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2997 non-null   str
 7   bedRoom          2997 non-null   int64
 8   bathroom         2997 non-null   int64
 9   balcony          2997 non-null   object
 10  additionalRoom   2997 non-null   str
 11  address          2991 non-null   str
 12  floorNum         2995 non-null   object
 13  facing           2123 non-null   str
 14  agePossession    2996 non-null   str
 15  nearbyLocations  2906 non-null   str
 16  description      2997 non-null   str
 17  furnishDetails   2200 non-null   str
 18  features         2590 non-null   str
 19  rating           2668 non-null   str
dtypes: float64(3), int64(2), object(2), str(13)
memory usage: 5.2+ MB

In [71]:
df.to_csv('flats_cleaned.csv',index=False)